export const ArtForms = [
  { spa: "pintura", eng: "painting", hint: "", id: "HAU895" },
  { spa: "escultura", eng: "sculpture", hint: "", id: "OMN356" },
  { spa: "dibujo", eng: "drawing", hint: "", id: "BLK562" },
  { spa: "fotografía", eng: "photography", hint: "", id: "SHE942" },
  { spa: "grabado", eng: "printmaking", hint: "", id: "TYH841" },
  { spa: "collage", eng: "collage", hint: "", id: "TEL275" },
  { spa: "cerámica", eng: "pottery", hint: "", id: "LRO203" },
  { spa: "cerámica", eng: "ceramics", hint: "", id: "XYO895" },
  { spa: "escultura en madera", eng: "carving", hint: "", id: "CDM025" },
  { spa: "grabado", eng: "engraving", hint: "", id: "RCM004" },
  { spa: "aguafuerte", eng: "etching", hint: "", id: "GGK032" },
  { spa: "xilografía", eng: "woodcut", hint: "", id: "OLD819" },
  { spa: "instalación", eng: "installation", hint: "", id: "ARW989" },
  { spa: "performance", eng: "performance", hint: "", id: "JTG875" },
  { spa: "danza", eng: "dance", hint: "", id: "UJP114" },
  { spa: "teatro", eng: "theater", hint: "", id: "SZB228" },
  { spa: "cine", eng: "film", hint: "", id: "ZBG127" },
  { spa: "música", eng: "music", hint: "", id: "GOS678" },
  { spa: "literatura", eng: "literature", hint: "", id: "ZLK204" },
  { spa: "poesía", eng: "poetry", hint: "", id: "TPH429" },
  { spa: "prosa", eng: "prose", hint: "", id: "KUU969" },
  { spa: "novela", eng: "novel", hint: "", id: "SJE744" },
  { spa: "cuento", eng: "short story", hint: "", id: "ENB345" },
  { spa: "obra de teatro", eng: "play", hint: "", id: "OQV765" },
  { spa: "novela", eng: "novel", hint: "", id: "UKE350" },
  { spa: "biografía", eng: "biography", hint: "", id: "UQM550" },
  { spa: "autobiografía", eng: "autobiography", hint: "", id: "XTV756" },
  { spa: "ensayo", eng: "essay", hint: "", id: "ORH209" },
  { spa: "artículo", eng: "article", hint: "", id: "ZFP462" },
  { spa: "crítica", eng: "critique", hint: "", id: "UCD269" },
  { spa: "periodismo", eng: "journalism", hint: "", id: "IPS447" },
];
