export const Beverages = [
  { spa: "café", eng: "coffee", hint: "", id: "HYN737" },
  { spa: "té", eng: "tea", hint: "", id: "OUF739" },
  { spa: "refresco", eng: "soda", hint: "", id: "XBA843" },
  { spa: "jugo", eng: "juice", hint: "", id: "BSR616" },
  { spa: "leche", eng: "milk", hint: "", id: "KBQ959" },
  { spa: "agua", eng: "water", hint: "", id: "LWG053" },
  { spa: "cerveza", eng: "beer", hint: "", id: "XAY131" },
  { spa: "vino", eng: "wine", hint: "", id: "OVU517" },
  { spa: "licores", eng: "spirits", hint: "", id: "GLG517" },
  { spa: "coctel", eng: "cocktail", hint: "", id: "HRN740" },
  { spa: "smoothie", eng: "smoothie", hint: "", id: "DRT788" },
  { spa: "licor", eng: "liqueur", hint: "", id: "NGO018" },
  { spa: "champán", eng: "champagne", hint: "", id: "JUO692" },
  { spa: "bebida energética", eng: "energy drink", hint: "", id: "HHL151" },
  { spa: "refresco", eng: "soft drink", hint: "", id: "XFX291" },
  { spa: "limonada", eng: "lemonade", hint: "", id: "JDQ288" },
  { spa: "sidra", eng: "cider", hint: "", id: "YEJ556" },
  {
    spa: "chocolate caliente",
    eng: "hot chocolate",
    hint: "",
    id: "NYO808",
  },
  { spa: "espresso", eng: "espresso", hint: "", id: "XTS957" },
  { spa: "café con leche", eng: "latte", hint: "", id: "KOU066" },
  { spa: "cappuccino", eng: "cappuccino", hint: "", id: "OKF791" },
  { spa: "americano", eng: "americano", hint: "", id: "SEL573" },
  { spa: "chai", eng: "chai", hint: "", id: "PRM678" },
  { spa: "matcha", eng: "matcha", hint: "", id: "XUU694" },
  { spa: "ponche de frutas", eng: "fruit punch", hint: "", id: "ELN774" },
  { spa: "sangría", eng: "sangria", hint: "", id: "GIC632" },
  { spa: "ponche", eng: "punch", hint: "", id: "SWW898" },
  { spa: "mimosa", eng: "mimosa", hint: "", id: "NRK747" },
  { spa: "batido", eng: "shake", hint: "", id: "HMU641" },
  { spa: "té de oolong", eng: "oolong", hint: "", id: "BKU068" },
  { spa: "té helado", eng: "iced tea", hint: "", id: "PUG504" },
  { spa: "moccha", eng: "mocha", hint: "", id: "GLF757" },
];
