export const ElectronicDevices = [
  { spa: "computadora", eng: "computer", hint: "", id: "XPP233" },
  {
    spa: "teléfono inteligente",
    eng: "smartphone",
    hint: "",
    id: "ASN004",
  },
  { spa: "tableta", eng: "tablet", hint: "", id: "HXZ669" },
  { spa: "computadora portátil", eng: "laptop", hint: "", id: "IQK320" },
  {
    spa: "computadora de escritorio",
    eng: "desktop",
    hint: "",
    id: "XZX306",
  },
  { spa: "servidor", eng: "server", hint: "", id: "NGA723" },
  { spa: "monitor", eng: "monitor", hint: "", id: "YAY931" },
  { spa: "teclado", eng: "keyboard", hint: "", id: "ELU609" },
  { spa: "ratón", eng: "mouse", hint: "", id: "ZFO932" },
  { spa: "audífonos", eng: "headphones", hint: "", id: "YOK413" },
  { spa: "bocina", eng: "speaker", hint: "", id: "BRA249" },
  { spa: "enrutador", eng: "router", hint: "", id: "KWZ873" },
  { spa: "módem", eng: "modem", hint: "", id: "MJT070" },
  { spa: "impresora", eng: "printer", hint: "", id: "GCN923" },
  { spa: "escáner", eng: "scanner", hint: "", id: "ZUF298" },
  { spa: "proyector", eng: "projector", hint: "", id: "FYH494" },
  { spa: "disco duro", eng: "hard drive", hint: "", id: "HXR120" },
  { spa: "memoria USB", eng: "flash drive", hint: "", id: "KVE563" },
  { spa: "tarjeta SD", eng: "SD card", hint: "", id: "UCC858" },
  { spa: "reloj inteligente", eng: "smartwatch", hint: "", id: "UQM184" },
  {
    spa: "rastreador de actividad física",
    eng: "fitness tracker",
    hint: "",
    id: "KMZ384",
  },
  { spa: "cámara digital", eng: "digital camera", hint: "", id: "QAR090" },
  { spa: "cámara web", eng: "webcam", hint: "", id: "WBP405" },
  { spa: "micrófono", eng: "microphone", hint: "", id: "YIS923" },
  {
    spa: "dispositivo Bluetooth",
    eng: "Bluetooth device",
    hint: "",
    id: "IFV566",
  },
  {
    spa: "dispositivo portátil",
    eng: "wearable device",
    hint: "",
    id: "KAQ937",
  },
  { spa: "fableta", eng: "phablet", hint: "", id: "RPA951" },
  {
    spa: "disco duro externo",
    eng: "external hard drive",
    hint: "",
    id: "VXJ726",
  },
  {
    spa: "consola de videojuegos",
    eng: "gaming console",
    hint: "",
    id: "ZOB383",
  },
  {
    spa: "visores de realidad virtual",
    eng: "virtual reality headset",
    hint: "",
    id: "NKE662",
  },
  {
    spa: "gafas de realidad aumentada",
    eng: "augmented reality glasses",
    hint: "",
    id: "RLV331",
  },
  { spa: "cámara de acción", eng: "action camera", hint: "", id: "UVJ926" },
  { spa: "lector electrónico", eng: "e-reader", hint: "", id: "FQK231" },
  {
    spa: "teléfono satelital",
    eng: "satellite phone",
    hint: "",
    id: "ASD237",
  },
  { spa: "pluma digital", eng: "digital pen", hint: "", id: "TBP342" },
  { spa: "robot", eng: "robot", hint: "", id: "OWD506" },
  { spa: "dron", eng: "drone", hint: "", id: "ZYD923" },
  { spa: "dispositivo GPS", eng: "GPS device", hint: "", id: "CUR009" },
  { spa: "sistema de alarma", eng: "alarm system", hint: "", id: "MNU997" },
  {
    spa: "dispositivo inteligente para el hogar",
    eng: "smart home device",
    hint: "",
    id: "DZF209",
  },
];
