export const FarmAnimals = [
  { spa: "vaca", eng: "cow", hint: "", id: "HYT438" },
  { spa: "cerdo", eng: "pig", hint: "", id: "USU212" },
  { spa: "pollo", eng: "chicken", hint: "", id: "ITL873" },
  { spa: "caballo", eng: "horse", hint: "", id: "QJG419" },
  { spa: "oveja", eng: "sheep", hint: "", id: "XHJ320" },
  { spa: "cabra", eng: "goat", hint: "", id: "IAB604" },
  { spa: "pato", eng: "duck", hint: "", id: "ONB057" },
  { spa: "gallo", eng: "rooster", hint: "", id: "PZJ027" },
  { spa: "burro", eng: "donkey", hint: "", id: "QUA864" },
  { spa: "pavo", eng: "turkey", hint: "", id: "UCF815" },
  { spa: "conejo", eng: "rabbit", hint: "", id: "HFL278" },
  { spa: "perro", eng: "dog", hint: "", id: "EBJ764" },
  { spa: "gato", eng: "cat", hint: "", id: "AUD449" },
  { spa: "ganso", eng: "goose", hint: "", id: "OJB577" },
  { spa: "llama", eng: "llama", hint: "", id: "QAZ825" },
  { spa: "alpaca", eng: "alpaca", hint: "", id: "QWI268" },
  { spa: "conejillo de indias", eng: "guinea pig", hint: "", id: "JQL862" },
  { spa: "hurón", eng: "ferret", hint: "", id: "CYN644" },
  { spa: "mula", eng: "mule", hint: "", id: "NXQ397" },
  { spa: "pony", eng: "pony", hint: "", id: "QJK010" },
  { spa: "carnero", eng: "ram", hint: "", id: "UMS899" },
  { spa: "toro", eng: "bull", hint: "", id: "DZQ680" },
  { spa: "jabalí", eng: "boar", hint: "", id: "GZF669" },
  { spa: "oveja", eng: "ewe", hint: "", id: "TIP303" },
  { spa: "ganso macho", eng: "gander", hint: "", id: "TLL217" },
  { spa: "cerda", eng: "sow", hint: "", id: "MAJ976" },
  { spa: "venado hembra", eng: "doe", hint: "", id: "RKI268" },
  { spa: "semental", eng: "stallion", hint: "", id: "YVD588" },
  { spa: "gallina", eng: "hen", hint: "", id: "DHH686" },
  { spa: "pato macho", eng: "drake", hint: "", id: "RML623" },
  { spa: "ovino castrado", eng: "wether", hint: "", id: "FSH775" },
  { spa: "semental", eng: "stallion", hint: "", id: "BSO610" },
  { spa: "yegua de cría", eng: "broodmare", hint: "", id: "QWV072" },
  { spa: "cabra nodriza", eng: "nanny goat", hint: "", id: "DUV593" },
  { spa: "gato macho", eng: "tomcat", hint: "", id: "LDZ747" },
  { spa: "potranca", eng: "filly", hint: "", id: "JPR460" },
  { spa: "caballo castrado", eng: "gelding", hint: "", id: "ALM638" },
  { spa: "cordera", eng: "ewe lamb", hint: "", id: "MYS120" },
  { spa: "cerdo", eng: "hog", hint: "", id: "BVV201" },
  { spa: "caballo de tiro", eng: "dray horse", hint: "", id: "CKZ629" },
  { spa: "Brahman", eng: "Brahman", hint: "", id: "JHA459" },
];
