export const HealthAndMedicalTerms = [
  { spa: "salud", eng: "health", hint: "", id: "WXM780" },
  { spa: "cuerpo", eng: "body", hint: "", id: "VLV680" },
  { spa: "bienestar", eng: "wellness", hint: "", id: "QPL398" },
  { spa: "bienestar", eng: "wellbeing", hint: "", id: "EQF478" },
  { spa: "fitness", eng: "fitness", hint: "", id: "OFR756" },
  { spa: "nutrición", eng: "nutrition", hint: "", id: "EZB027" },
  { spa: "ejercicio", eng: "exercise", hint: "", id: "XPK489" },
  { spa: "dieta", eng: "diet", hint: "", id: "GQA199" },
  { spa: "síntoma", eng: "symptom", hint: "", id: "YEF354" },
  { spa: "hospital", eng: "hospital", hint: "", id: "CXL062" },
  { spa: "doctor", eng: "doctor", hint: "", id: "IBH615" },
  { spa: "enfermera", eng: "nurse", hint: "", id: "QLU855" },
  { spa: "paciente", eng: "patient", hint: "", id: "LIQ887" },
  { spa: "médico", eng: "medical", hint: "", id: "REH938" },
  { spa: "tratamiento", eng: "treatment", hint: "", id: "NDV545" },
  { spa: "receta", eng: "prescription", hint: "", id: "EMT023" },
  { spa: "medicamento", eng: "medication", hint: "", id: "HWL726" },
  { spa: "terapia", eng: "therapy", hint: "", id: "KZF404" },
  { spa: "cirugía", eng: "surgery", hint: "", id: "QYM343" },
  { spa: "lesión", eng: "injury", hint: "", id: "KUO757" },
  { spa: "enfermedad", eng: "illness", hint: "", id: "PFM147" },
  { spa: "enfermedad", eng: "disease", hint: "", id: "RVJ217" },
  { spa: "alergia", eng: "allergy", hint: "", id: "HXU214" },
  { spa: "sistema inmune", eng: "immune system", hint: "", id: "OKB825" },
  { spa: "vacuna", eng: "vaccine", hint: "", id: "AHR960" },
  { spa: "farmacia", eng: "pharmacy", hint: "", id: "ZUO471" },
  { spa: "emergencia", eng: "emergency", hint: "", id: "GYB037" },
  { spa: "terapia", eng: "therapy", hint: "", id: "PCU644" },
  { spa: "consejería", eng: "counseling", hint: "", id: "RJE292" },
  { spa: "enfermo", eng: "sick", hint: "", id: "ABR640" },
  { spa: "infección", eng: "infection", hint: "", id: "INF925" },
  { spa: "dolor", eng: "pain", hint: "", id: "MVN139" },
  { spa: "diagnóstico", eng: "diagnosis", hint: "", id: "ZBM121" },
  { spa: "cuidado", eng: "care", hint: "", id: "IEA652" },
  { spa: "recuperación", eng: "recovery", hint: "", id: "WRA654" },
  { spa: "prueba", eng: "test", hint: "", id: "FYG590" },
  { spa: "virus", eng: "virus", hint: "", id: "JKP263" },
  { spa: "bacteria", eng: "bacteria", hint: "", id: "LLB046" },
  { spa: "cepa", eng: "strain", hint: "", id: "MTJ082" },
  { spa: "herida", eng: "wound", hint: "", id: "HLI420" },
  { spa: "llaga", eng: "sore", hint: "", id: "UQY312" },
  { spa: "tos", eng: "cough", hint: "", id: "ZGR461" },
  { spa: "dolor de cabeza", eng: "headache", hint: "", id: "JZH164" },
  { spa: "fiebre", eng: "fever", hint: "", id: "HOT383" },
  { spa: "sangre", eng: "blood", hint: "", id: "YDZ457" },
  { spa: "presión", eng: "pressure", hint: "", id: "TNS690" },
  { spa: "temperatura", eng: "temperature", hint: "", id: "SMK279" },
  { spa: "escalofrío", eng: "chill", hint: "", id: "VBK490" },
  { spa: "sudor", eng: "sweat", hint: "", id: "ABL612" },
  { spa: "corazón", eng: "heart", hint: "", id: "FWM934" },
  { spa: "pulmones", eng: "lungs", hint: "", id: "QKE728" },
  { spa: "cerebro", eng: "brain", hint: "", id: "JWN621" },
  { spa: "huesos", eng: "bones", hint: "", id: "ZYJ052" },
  { spa: "músculos", eng: "muscles", hint: "", id: "UYP375" },
  { spa: "órganos", eng: "organs", hint: "", id: "LQA436" },
  { spa: "vasos sanguíneos", eng: "vessels", hint: "", id: "DXB408" },
  { spa: "células", eng: "cells", hint: "", id: "DXY874" },
  { spa: "tejido", eng: "tissue", hint: "", id: "GXF843" },
  { spa: "articulación", eng: "joint", hint: "", id: "PXO771" },
  { spa: "piel", eng: "skin", hint: "", id: "AVA588" },
  { spa: "cabello", eng: "hair", hint: "", id: "RUA308" },
  { spa: "uñas", eng: "nails", hint: "", id: "MWF709" },
  { spa: "dientes", eng: "teeth", hint: "", id: "XSU916" },
  { spa: "boca", eng: "mouth", hint: "", id: "ECX411" },
  { spa: "garganta", eng: "throat", hint: "", id: "FEO001" },
  { spa: "estómago", eng: "stomach", hint: "", id: "YRB498" },
  { spa: "hígado", eng: "liver", hint: "", id: "LJZ594" },
  { spa: "riñón", eng: "kidney", hint: "", id: "WFN224" },
  { spa: "cerebro", eng: "brain", hint: "", id: "PYQ942" },
  { spa: "corazón", eng: "heart", hint: "", id: "XRH791" },
  { spa: "pulmones", eng: "lungs", hint: "", id: "GDG647" },
  { spa: "intestino", eng: "intestine", hint: "", id: "ROU048" },
  { spa: "columna vertebral", eng: "spine", hint: "", id: "HCW449" },
  {
    spa: "corriente sanguínea",
    eng: "bloodstream",
    hint: "",
    id: "UEL321",
  },
  { spa: "esqueleto", eng: "skeleton", hint: "", id: "ECK008" },
  { spa: "digestión", eng: "digestion", hint: "", id: "PLG779" },
  { spa: "circulación", eng: "circulation", hint: "", id: "KAU977" },
  {
    spa: "sistema respiratorio",
    eng: "respiratory system",
    hint: "",
    id: "VMP985",
  },
  {
    spa: "sistema nervioso",
    eng: "nervous system",
    hint: "",
    id: "XVF751",
  },
  {
    spa: "sistema inmunológico",
    eng: "immune system",
    hint: "",
    id: "IIZ438",
  },
  {
    spa: "sistema cardiovascular",
    eng: "cardiovascular system",
    hint: "",
    id: "OKC170",
  },
  {
    spa: "sistema muscular",
    eng: "muscular system",
    hint: "",
    id: "EUK795",
  },
  {
    spa: "sistema esquelético",
    eng: "skeletal system",
    hint: "",
    id: "ZDF329",
  },
  {
    spa: "sistema endocrino",
    eng: "endocrine system",
    hint: "",
    id: "OZO270",
  },
  {
    spa: "sistema tegumentario",
    eng: "integumentary system",
    hint: "",
    id: "NBB193",
  },
  { spa: "órganos", eng: "organs", hint: "", id: "KNA229" },
  { spa: "anatomía", eng: "anatomy", hint: "", id: "YBI305" },
  { spa: "fisiología", eng: "physiology", hint: "", id: "RPL980" },
];
