export const InternationalRelations = [
  { spa: "tratado", eng: "treaty", hint: "", id: "MYR309" },
  { spa: "embajada", eng: "embassy", hint: "", id: "RGN998" },
  { spa: "diplomacia", eng: "diplomacy", hint: "", id: "LTG992" },
  { spa: "alianza", eng: "alliance", hint: "", id: "GJB817" },
  { spa: "negociación", eng: "negotiation", hint: "", id: "SZQ989" },
  { spa: "conflicto", eng: "conflict", hint: "", id: "TYD482" },
  { spa: "resolución", eng: "resolution", hint: "", id: "PMF237" },
  { spa: "sanción", eng: "sanction", hint: "", id: "UZZ026" },
  { spa: "tensión", eng: "tension", hint: "", id: "XUP040" },
  { spa: "acuerdo", eng: "agreement", hint: "", id: "RXQ055" },
  { spa: "cumbre", eng: "summit", hint: "", id: "LPO793" },
  { spa: "alianza", eng: "alliance", hint: "", id: "DUB312" },
  { spa: "coalición", eng: "coalition", hint: "", id: "CNH788" },
  { spa: "mediación", eng: "mediation", hint: "", id: "GZK489" },
  { spa: "anexión", eng: "annexation", hint: "", id: "EYH913" },
  { spa: "reconciliación", eng: "reconciliation", hint: "", id: "NUB735" },
  { spa: "alto al fuego", eng: "ceasefire", hint: "", id: "CGJ050" },
  { spa: "diplomático", eng: "diplomat", hint: "", id: "MBJ956" },
  { spa: "delegación", eng: "delegation", hint: "", id: "VGH771" },
  { spa: "bilateral", eng: "bilateral", hint: "", id: "NFD414" },
  { spa: "multilateral", eng: "multilateral", hint: "", id: "BHU693" },
  { spa: "soberanía", eng: "sovereignty", hint: "", id: "PEV956" },
  { spa: "guerra", eng: "warfare", hint: "", id: "GEN616" },
  { spa: "reparación", eng: "reparation", hint: "", id: "OTP056" },
  { spa: "territorio", eng: "territory", hint: "", id: "JHP005" },
  { spa: "espionaje", eng: "espionage", hint: "", id: "TMW733" },
  { spa: "golpe de estado", eng: "coup", hint: "", id: "UKA400" },
  { spa: "acuerdo", eng: "accord", hint: "", id: "BXB687" },
  { spa: "ratificación", eng: "ratification", hint: "", id: "AEW473" },
  {
    spa: "derecho internacional",
    eng: "international law",
    hint: "",
    id: "QDX561",
  },
  {
    spa: "departamento de estado",
    eng: "department of state",
    hint: "",
    id: "BYO943",
  },
];
