export const MealsAndDining = [
  { spa: "aperitivo", eng: "appetizer", hint: "", id: "SDD262" },
  { spa: "plato principal", eng: "main course", hint: "", id: "JCI145" },
  { spa: "entrada", eng: "entree", hint: "", id: "VBC039" },
  { spa: "acompañamiento", eng: "side dish", hint: "", id: "GMY709" },
  { spa: "postre", eng: "dessert", hint: "", id: "AYO384" },
  { spa: "bebida", eng: "beverage", hint: "", id: "NSU093" },
  { spa: "sopa", eng: "soup", hint: "", id: "OAJ306" },
  { spa: "ensalada", eng: "salad", hint: "", id: "HDQ783" },
  { spa: "entrada", eng: "starter", hint: "", id: "CJN481" },
  { spa: "bocadillo", eng: "snack", hint: "", id: "SVZ534" },
  { spa: "pastelito", eng: "pastry", hint: "", id: "UWN015" },
  { spa: "pan", eng: "bread", hint: "", id: "MZL664" },
  { spa: "sándwich", eng: "sandwich", hint: "", id: "DAQ009" },
  { spa: "hamburguesa", eng: "burger", hint: "", id: "OAJ386" },
  { spa: "pizza", eng: "pizza", hint: "", id: "TYY767" },
  { spa: "pasta", eng: "pasta", hint: "", id: "BKK926" },
  { spa: "arroz", eng: "rice", hint: "", id: "AUE587" },
  { spa: "fideo", eng: "noodle", hint: "", id: "JHS131" },
  { spa: "curry", eng: "curry", hint: "", id: "QRN197" },
  { spa: "guiso", eng: "stew", hint: "", id: "DEE359" },
  { spa: "asado", eng: "roast", hint: "", id: "ZMM210" },
  { spa: "parrilla", eng: "grill", hint: "", id: "FEC061" },
  { spa: "freír", eng: "fry", hint: "", id: "BJL584" },
  { spa: "saltear", eng: "saute", hint: "", id: "YIA879" },
  { spa: "hornear", eng: "bake", hint: "", id: "ICJ249" },
  { spa: "cocinar", eng: "cook", hint: "", id: "XYY401" },
  { spa: "comida", eng: "meal", hint: "", id: "LEH599" },
  { spa: "plato", eng: "plate", hint: "", id: "IXD114" },
  { spa: "platillo", eng: "dish", hint: "", id: "QMO772" },
  { spa: "tazón", eng: "bowl", hint: "", id: "GNH958" },
  { spa: "taza", eng: "cup", hint: "", id: "KCN483" },
  { spa: "tenedor", eng: "fork", hint: "", id: "KNN387" },
  { spa: "cuchillo", eng: "knife", hint: "", id: "GAG336" },
  { spa: "cuchara", eng: "spoon", hint: "", id: "VIT732" },
  { spa: "servilleta", eng: "napkin", hint: "", id: "FVC280" },
  { spa: "menú", eng: "menu", hint: "", id: "ZWT287" },
  { spa: "chef", eng: "chef", hint: "", id: "YGB566" },
  { spa: "mesero", eng: "server", hint: "", id: "BZA315" },
  { spa: "cliente", eng: "customer", hint: "", id: "QTA423" },
];
