export const NaturalElements = [
  { spa: "árbol", eng: "tree", hint: "", id: "TMY893" },
  { spa: "flor", eng: "flower", hint: "", id: "ZJH555" },
  { spa: "planta", eng: "plant", hint: "", id: "HTA802" },
  { spa: "pasto", eng: "grass", hint: "", id: "LTX542" },
  { spa: "arbusto", eng: "bush", hint: "", id: "XNR153" },
  { spa: "rama", eng: "branch", hint: "", id: "XZS120" },
  { spa: "hoja", eng: "leaf", hint: "", id: "AFF027" },
  { spa: "raíz", eng: "root", hint: "", id: "IET876" },
  { spa: "tronco", eng: "log", hint: "", id: "PBA986" },
  { spa: "ramita", eng: "twig", hint: "", id: "SOT284" },
  { spa: "espina", eng: "thorn", hint: "", id: "FCW445" },
  { spa: "piña", eng: "pinecone", hint: "", id: "KOH101" },
  { spa: "corteza", eng: "bark", hint: "", id: "ZEZ542" },
  { spa: "tronco", eng: "trunk", hint: "", id: "EFT469" },
  { spa: "pétalo", eng: "petal", hint: "", id: "TNZ047" },
  { spa: "tallo", eng: "stem", hint: "", id: "UHS994" },
  { spa: "flor", eng: "blossom", hint: "", id: "CXS792" },
  { spa: "maleza", eng: "weed", hint: "", id: "RBH539" },
  { spa: "helecho", eng: "fern", hint: "", id: "IDY708" },
  { spa: "musgo", eng: "moss", hint: "", id: "FIU587" },
  { spa: "alga marina", eng: "seaweed", hint: "", id: "QQG849" },
  { spa: "coral", eng: "coral", hint: "", id: "HCQ023" },
  { spa: "concha", eng: "shell", hint: "", id: "FGI119" },
  { spa: "piedrecita", eng: "pebble", hint: "", id: "IXC758" },
  { spa: "roca", eng: "rock", hint: "", id: "AZW889" },
  { spa: "piedra", eng: "stone", hint: "", id: "MLI994" },
  { spa: "montaña", eng: "mountain", hint: "", id: "XHP790" },
  { spa: "colina", eng: "hill", hint: "", id: "JQQ181" },
  { spa: "valle", eng: "valley", hint: "", id: "IXD172" },
  { spa: "cañón", eng: "canyon", hint: "", id: "OSG280" },
  { spa: "meseta", eng: "plateau", hint: "", id: "UOE908" },
  { spa: "acantilado", eng: "cliff", hint: "", id: "QFE771" },
  { spa: "cueva", eng: "cave", hint: "", id: "NSU628" },
  { spa: "arroyo", eng: "creek", hint: "", id: "LYF848" },
  { spa: "arroyo", eng: "stream", hint: "", id: "IVB407" },
  { spa: "río", eng: "river", hint: "", id: "BCH338" },
  { spa: "lago", eng: "lake", hint: "", id: "TON944" },
  { spa: "estanque", eng: "pond", hint: "", id: "FGN879" },
  { spa: "cascada", eng: "waterfall", hint: "", id: "PEF471" },
  { spa: "océano", eng: "ocean", hint: "", id: "KHL248" },
  { spa: "mar", eng: "sea", hint: "", id: "VLM712" },
  { spa: "playa", eng: "beach", hint: "", id: "PTA335" },
  { spa: "costa", eng: "coast", hint: "", id: "YPF085" },
  { spa: "orilla", eng: "shore", hint: "", id: "HXN840" },
  { spa: "isla", eng: "island", hint: "", id: "KBO910" },
  { spa: "península", eng: "peninsula", hint: "", id: "FKN398" },
  { spa: "volcán", eng: "volcano", hint: "", id: "YIA233" },
  { spa: "geiser", eng: "geyser", hint: "", id: "BYS715" },
  { spa: "glaciar", eng: "glacier", hint: "", id: "NTE481" },
  { spa: "avalancha", eng: "avalanche", hint: "", id: "AWF383" },
  { spa: "huracán", eng: "hurricane", hint: "", id: "OSE992" },
  { spa: "tornado", eng: "tornado", hint: "", id: "ANE011" },
  {
    spa: "tormenta eléctrica",
    eng: "thunderstorm",
    hint: "",
    id: "FKE462",
  },
  { spa: "relámpago", eng: "lightning", hint: "", id: "LGS551" },
  { spa: "lluvia", eng: "rain", hint: "", id: "TFY784" },
  { spa: "nieve", eng: "snow", hint: "", id: "IVM786" },
  { spa: "granizo", eng: "hail", hint: "", id: "YTV512" },
  { spa: "niebla", eng: "fog", hint: "", id: "HTY746" },
  { spa: "neblina", eng: "mist", hint: "", id: "HFH907" },
  { spa: "nube", eng: "cloud", hint: "", id: "IJL385" },
  { spa: "arcoíris", eng: "rainbow", hint: "", id: "SES118" },
  { spa: "amanecer", eng: "sunrise", hint: "", id: "TOK350" },
  { spa: "atardecer", eng: "sunset", hint: "", id: "JJW316" },
  { spa: "estrella", eng: "star", hint: "", id: "UBD554" },
  { spa: "luna", eng: "moon", hint: "", id: "OUQ564" },
  { spa: "planeta", eng: "planet", hint: "", id: "UIG690" },
  { spa: "galaxia", eng: "galaxy", hint: "", id: "DIL153" },
  { spa: "constelación", eng: "constellation", hint: "", id: "GTZ392" },
];
