export const ReligiousTextsAndSymbols = [
  { spa: "Biblia", eng: "Bible", hint: "", id: "OSR542" },
  { spa: "Corán", eng: "Quran", hint: "", id: "QNA444" },
  { spa: "Torá", eng: "Torah", hint: "", id: "KDH196" },
  { spa: "Evangelio", eng: "Gospel", hint: "", id: "NSB322" },
  { spa: "Vedas", eng: "Vedas", hint: "", id: "ZDM429" },
  { spa: "Sutras", eng: "Sutras", hint: "", id: "RGL241" },
  { spa: "Tripitaka", eng: "Tripitaka", hint: "", id: "DYU521" },
  { spa: "Hadiz", eng: "Hadith", hint: "", id: "SVG136" },
  { spa: "Talmud", eng: "Talmud", hint: "", id: "GRR754" },
  { spa: "Salmos", eng: "Psalms", hint: "", id: "IXO044" },
  { spa: "Mantra", eng: "Mantra", hint: "", id: "NXY742" },
  { spa: "Corán", eng: "Koran", hint: "", id: "DKE038" },
  { spa: "Escritura", eng: "Scripture", hint: "", id: "BBV229" },
  { spa: "Pergaminos", eng: "Scrolls", hint: "", id: "OOA605" },
  { spa: "Tablas", eng: "Tablets", hint: "", id: "FHO040" },
  { spa: "Cruz", eng: "Cross", hint: "", id: "WQJ212" },
  {
    spa: "Estrella de David",
    eng: "Star of David",
    hint: "",
    id: "IHX364",
  },
  { spa: "Media luna", eng: "Crescent", hint: "", id: "JHS237" },
  { spa: "Ictios", eng: "Ichthys", hint: "", id: "VEJ179" },
  { spa: "Rosario", eng: "Rosary", hint: "", id: "XBL266" },
  { spa: "Cáliz", eng: "Chalice", hint: "", id: "OYV071" },
  { spa: "Altar", eng: "Altar", hint: "", id: "QXX640" },
  { spa: "Vela", eng: "Candle", hint: "", id: "PQM723" },
  { spa: "Incienso", eng: "Incense", hint: "", id: "WSC200" },
  { spa: "Reliquia", eng: "Relic", hint: "", id: "JWM330" },
  { spa: "Talismán", eng: "Talisman", hint: "", id: "OES320" },
  { spa: "Amuleto", eng: "Amulet", hint: "", id: "TXB754" },
  { spa: "Mandala", eng: "Mandala", hint: "", id: "MAD239" },
  { spa: "Inciensario", eng: "Thurible", hint: "", id: "BZX022" },
  { spa: "Incensario", eng: "Censer", hint: "", id: "XMU494" },
  { spa: "Sacramento", eng: "Sacrament", hint: "", id: "OBN890" },
  { spa: "Rosario", eng: "Beads", hint: "", id: "BDP228" },
  { spa: "Santuario", eng: "Shrine", hint: "", id: "ZIQ481" },
  { spa: "Ídolo", eng: "Idol", hint: "", id: "XKW697" },
  { spa: "Estatua", eng: "Statue", hint: "", id: "CUT701" },
  { spa: "Ícono", eng: "Icon", hint: "", id: "QOG413" },
  { spa: "Diya", eng: "Diya", hint: "", id: "ZYR882" },
  { spa: "Mitras", eng: "Mitre", hint: "", id: "GRJ219" },
  { spa: "Liturgia", eng: "Liturgy", hint: "", id: "DBY913" },
  { spa: "Jamsa", eng: "Hamsa", hint: "", id: "CWY634" },
  { spa: "Mandorla", eng: "Mandorla", hint: "", id: "NHV806" },
  { spa: "Ankh", eng: "Ankh", hint: "", id: "VBQ050" },
  { spa: "Yin yang", eng: "Yin yang", hint: "", id: "BJQ421" },
  { spa: "Menorá", eng: "Menorah", hint: "", id: "JBL966" },
];
