export const ReligiousFiguresAndLeaders = [
  { spa: "profeta", eng: "prophet", hint: "", id: "IUY985" },
  { spa: "sacerdote", eng: "priest", hint: "", id: "NOI996" },
  { spa: "clero", eng: "clergy", hint: "", id: "WMX302" },
  { spa: "ministro", eng: "minister", hint: "", id: "YGU366" },
  { spa: "papa", eng: "pope", hint: "", id: "POQ347" },
  { spa: "capellán", eng: "chaplain", hint: "", id: "XVU531" },
  { spa: "monje", eng: "monk", hint: "", id: "JRD219" },
  { spa: "monja", eng: "nun", hint: "", id: "OLM439" },
  { spa: "obispo", eng: "bishop", hint: "", id: "OFB804" },
  { spa: "cardenal", eng: "cardinal", hint: "", id: "VXP163" },
  { spa: "clérigo", eng: "cleric", hint: "", id: "QMG930" },
  { spa: "imán", eng: "imam", hint: "", id: "JXB255" },
  { spa: "rabino", eng: "rabbi", hint: "", id: "NAK909" },
  { spa: "pastor", eng: "pastor", hint: "", id: "LVU227" },
  { spa: "diácono", eng: "deacon", hint: "", id: "CKR476" },
  { spa: "predicador", eng: "preacher", hint: "", id: "XUP986" },
  { spa: "evangelista", eng: "evangelist", hint: "", id: "MEW220" },
  { spa: "chamán", eng: "shaman", hint: "", id: "DTL330" },
  { spa: "pujari", eng: "pujari", hint: "", id: "EBC914" },
  { spa: "gurú", eng: "guru", hint: "", id: "ZBS459" },
];
