export const SchoolRelatedRoles = [
  { spa: "estudiante", eng: "student", hint: "", id: "CKN700" },
  { spa: "maestro", eng: "teacher", hint: "", id: "LHR072" },
  { spa: "director", eng: "principal", hint: "", id: "LEF929" },
  { spa: "director", eng: "headmaster", hint: "", id: "CPC007" },
  { spa: "directora", eng: "headmistress", hint: "", id: "HIT954" },
  { spa: "profesor", eng: "professor", hint: "", id: "JBW103" },
  { spa: "instructor", eng: "instructor", hint: "", id: "PFT331" },
  { spa: "conferencista", eng: "lecturer", hint: "", id: "IRI962" },
  { spa: "tutor", eng: "tutor", hint: "", id: "NSV271" },
  { spa: "consejero", eng: "counselor", hint: "", id: "ZVY120" },
  { spa: "bibliotecario", eng: "librarian", hint: "", id: "MDB415" },
  { spa: "administrador", eng: "administrator", hint: "", id: "UGE136" },
  { spa: "decano", eng: "dean", hint: "", id: "JZR866" },
  { spa: "supervisor", eng: "supervisor", hint: "", id: "BIP222" },
  { spa: "entrenador", eng: "coach", hint: "", id: "ITA026" },
  { spa: "educador", eng: "educator", hint: "", id: "TPG454" },
];
