export const SeasonalTerms = [
  { spa: "clima", eng: "weather", hint: "", id: "KXY568" },
  { spa: "estaciones", eng: "seasons", hint: "", id: "AVF010" },
  { spa: "sol", eng: "sun", hint: "", id: "HLJ209" },
  { spa: "lluvia", eng: "rain", hint: "", id: "EMB135" },
  { spa: "nieve", eng: "snow", hint: "", id: "KLW679" },
  { spa: "granizo", eng: "hail", hint: "", id: "PHD005" },
  { spa: "tormenta", eng: "storm", hint: "", id: "FEZ372" },
  { spa: "relámpago", eng: "lightning", hint: "", id: "ZRS484" },
  { spa: "trueno", eng: "thunder", hint: "", id: "YEO029" },
  { spa: "niebla", eng: "fog", hint: "", id: "OPA025" },
  { spa: "viento", eng: "wind", hint: "", id: "FDF872" },
  { spa: "brisa", eng: "breeze", hint: "", id: "ISF856" },
  { spa: "ráfaga", eng: "gust", hint: "", id: "AYI382" },
  { spa: "neblina", eng: "mist", hint: "", id: "SSD582" },
  { spa: "húmedo", eng: "humid", hint: "", id: "DUQ775" },
  { spa: "humedad", eng: "humidity", hint: "", id: "GDZ872" },
  { spa: "rocío", eng: "dew", hint: "", id: "PDD821" },
  { spa: "temperatura", eng: "temperature", hint: "", id: "VPN825" },
  { spa: "nube", eng: "cloud", hint: "", id: "QBJ911" },
  { spa: "cielo", eng: "sky", hint: "", id: "PJQ507" },
  { spa: "arcoíris", eng: "rainbow", hint: "", id: "HCP254" },
  { spa: "escarcha", eng: "frost", hint: "", id: "HRS984" },
  { spa: "hielo", eng: "ice", hint: "", id: "SAC591" },
  { spa: "aguanieve", eng: "sleet", hint: "", id: "GJY561" },
  { spa: "llovizna", eng: "drizzle", hint: "", id: "JKO131" },
  { spa: "tormenta de nieve", eng: "blizzard", hint: "", id: "BKN238" },
  { spa: "tornado", eng: "tornado", hint: "", id: "QZK419" },
  { spa: "huracán", eng: "hurricane", hint: "", id: "ENW155" },
  { spa: "monzón", eng: "monsoon", hint: "", id: "GUX662" },
  { spa: "tifón", eng: "typhoon", hint: "", id: "LHT347" },
  { spa: "ciclón", eng: "cyclone", hint: "", id: "JDB695" },
  { spa: "sequía", eng: "drought", hint: "", id: "MDU853" },
  { spa: "ola de calor", eng: "heatwave", hint: "", id: "GGV397" },
  { spa: "frío", eng: "cold", hint: "", id: "FRK976" },
  { spa: "frialdad", eng: "chill", hint: "", id: "UDD215" },
  { spa: "niebla", eng: "fog", hint: "", id: "HSX102" },
  { spa: "bruma", eng: "haze", hint: "", id: "OBL062" },
  { spa: "smog", eng: "smog", hint: "", id: "CTL803" },
  { spa: "aguacero", eng: "downpour", hint: "", id: "FGL771" },
  { spa: "nublado", eng: "overcast", hint: "", id: "HQL191" },
  { spa: "brisa", eng: "breeze", hint: "", id: "BFT827" },
  { spa: "sol", eng: "sunshine", hint: "", id: "CXQ701" },
  { spa: "calor sofocante", eng: "scorch", hint: "", id: "ZGZ764" },
  { spa: "lluvia ligera", eng: "shower", hint: "", id: "CCD177" },
  { spa: "aguacero", eng: "downpour", hint: "", id: "NAK078" },
  { spa: "brisa", eng: "breeze", hint: "", id: "YUK475" },
  { spa: "tornado", eng: "tornado", hint: "", id: "PSH038" },
  { spa: "huracán", eng: "hurricane", hint: "", id: "AYI226" },
  { spa: "monzón", eng: "monsoon", hint: "", id: "UYF245" },
  { spa: "tifón", eng: "typhoon", hint: "", id: "GYF245" },
  { spa: "ciclón", eng: "cyclone", hint: "", id: "SHJ392" },
];
