export const Pronouns = [
  { spanish: "yo", english: "I", guess: "unquizzed", hint: "", id: "CLL544" },
  { spanish: "tú", english: "you", guess: "unquizzed", hint: "", id: "ZJD751" },
  {
    spanish: "usted",
    english: "you",
    guess: "unquizzed",
    hint: "",
    id: "KOD154",
  },
  { spanish: "él", english: "he", guess: "unquizzed", hint: "", id: "QEK340" },
  {
    spanish: "ella",
    english: "she",
    guess: "unquizzed",
    hint: "",
    id: "KYY521",
  },
  {
    spanish: "nosotros",
    english: "we",
    guess: "unquizzed",
    hint: "",
    id: "GGI527",
  },
  {
    spanish: "nosotras",
    english: "we",
    guess: "unquizzed",
    hint: "",
    id: "HQZ749",
  },
  {
    spanish: "ustedes",
    english: "you all",
    guess: "unquizzed",
    hint: "",
    id: "BQK736",
  },
  {
    spanish: "vosotros",
    english: "you all",
    guess: "unquizzed",
    hint: "",
    id: "PUO040",
  },
  {
    spanish: "vosotras",
    english: "you all",
    guess: "unquizzed",
    hint: "",
    id: "YUV484",
  },
  {
    spanish: "ellos",
    english: "they",
    guess: "unquizzed",
    hint: "",
    id: "EEU927",
  },
  {
    spanish: "ellas",
    english: "they",
    guess: "unquizzed",
    hint: "",
    id: "MVX294",
  },
  {
    spanish: "mío",
    english: "mine",
    guess: "unquizzed",
    hint: "",
    id: "LFS556",
  },
  {
    spanish: "mía",
    english: "mine",
    guess: "unquizzed",
    hint: "",
    id: "GMC070",
  },
  {
    spanish: "mi",
    english: "mine",
    guess: "unquizzed",
    hint: "",
    id: "KMQ136",
  },
  {
    spanish: "míos",
    english: "mine",
    guess: "unquizzed",
    hint: "",
    id: "PRB510",
  },
  {
    spanish: "tuyo",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "WHB132",
  },
  {
    spanish: "tuya",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "XBB200",
  },
  {
    spanish: "tuyos",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "BSY885",
  },
  {
    spanish: "tuyas",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "MPO161",
  },
  {
    spanish: "suyo",
    english: "his/hers/yours",
    guess: "unquizzed",
    hint: "",
    id: "JEV014",
  },
  {
    spanish: "suya",
    english: "his/hers/yours",
    guess: "unquizzed",
    hint: "",
    id: "CVC899",
  },
  {
    spanish: "suyos",
    english: "his/hers/yours",
    guess: "unquizzed",
    hint: "",
    id: "OEW887",
  },
  {
    spanish: "suyas",
    english: "his/hers/yours",
    guess: "unquizzed",
    hint: "",
    id: "FLR467",
  },
  {
    spanish: "nuestro",
    english: "ours",
    guess: "unquizzed",
    hint: "",
    id: "VOV096",
  },
  {
    spanish: "nuestra",
    english: "ours",
    guess: "unquizzed",
    hint: "",
    id: "VIO420",
  },
  {
    spanish: "nuestros",
    english: "ours",
    guess: "unquizzed",
    hint: "",
    id: "JMJ981",
  },
  {
    spanish: "nuestras",
    english: "ours",
    guess: "unquizzed",
    hint: "",
    id: "RQG597",
  },
  {
    spanish: "vuestro",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "VED050",
  },
  {
    spanish: "vuestra",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "ZKF178",
  },
  {
    spanish: "vuestros",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "AXW334",
  },
  {
    spanish: "vuestras",
    english: "yours",
    guess: "unquizzed",
    hint: "",
    id: "NAX612",
  },
  {
    spanish: "mí",
    english: "myself",
    guess: "unquizzed",
    hint: "",
    id: "ZHJ295",
  },
  {
    spanish: "ti",
    english: "yourself",
    guess: "unquizzed",
    hint: "",
    id: "XOH057",
  },
  {
    spanish: "se",
    english: "himself/herself/yourself",
    guess: "unquizzed",
    hint: "",
    id: "ZVL770",
  },
  {
    spanish: "nosotros mismos",
    english: "ourselves",
    guess: "unquizzed",
    hint: "",
    id: "VVZ549",
  },
  {
    spanish: "ustedes mismos",
    english: "yourselves",
    guess: "unquizzed",
    hint: "",
    id: "XVE985",
  },
  {
    spanish: "sí mismos",
    english: "themselves/yourselves",
    guess: "unquizzed",
    hint: "",
    id: "YPZ851",
  },
  { spanish: "me", english: "me", guess: "unquizzed", hint: "", id: "JCZ470" },
  { spanish: "te", english: "you", guess: "unquizzed", hint: "", id: "VLR667" },
  {
    spanish: "lo",
    english: "him/it",
    guess: "unquizzed",
    hint: "",
    id: "NAA813",
  },
  {
    spanish: "la",
    english: "her/it",
    guess: "unquizzed",
    hint: "",
    id: "MEQ224",
  },
  { spanish: "nos", english: "us", guess: "unquizzed", hint: "", id: "BMT315" },
  {
    spanish: "ustedes",
    english: "you all",
    guess: "unquizzed",
    hint: "",
    id: "JVD851",
  },
  {
    spanish: "los",
    english: "them",
    guess: "unquizzed",
    hint: "",
    id: "RXK585",
  },
  {
    spanish: "las",
    english: "them",
    guess: "unquizzed",
    hint: "",
    id: "WNE552",
  },
  {
    spanish: "para mí",
    english: "to/for me",
    guess: "unquizzed",
    hint: "",
    id: "SUW943",
  },
  {
    spanish: "para ti",
    english: "to/for you",
    guess: "unquizzed",
    hint: "",
    id: "HFS688",
  },
  {
    spanish: "para él/ella/usted",
    english: "to/for him/her/you",
    guess: "unquizzed",
    hint: "",
    id: "XQN322",
  },
  {
    spanish: "para nosotros",
    english: "to/for us",
    guess: "unquizzed",
    hint: "",
    id: "PNL871",
  },
  {
    spanish: "para ustedes",
    english: "to/for you all",
    guess: "unquizzed",
    hint: "",
    id: "USS025",
  },
  {
    spanish: "para ellos/ellas/ustedes",
    english: "to/for them/you all",
    guess: "unquizzed",
    hint: "",
    id: "AEJ964",
  },
  {
    spanish: "este",
    english: "this",
    guess: "unquizzed",
    hint: "",
    id: "TPK564",
  },
  {
    spanish: "esta",
    english: "this",
    guess: "unquizzed",
    hint: "",
    id: "UWF771",
  },
  {
    spanish: "estos",
    english: "these",
    guess: "unquizzed",
    hint: "",
    id: "OEU154",
  },
  {
    spanish: "estas",
    english: "these",
    guess: "unquizzed",
    hint: "",
    id: "DHC274",
  },
  {
    spanish: "ese",
    english: "that",
    guess: "unquizzed",
    hint: "",
    id: "AWH851",
  },
  {
    spanish: "esa",
    english: "that",
    guess: "unquizzed",
    hint: "",
    id: "GAQ170",
  },
  {
    spanish: "esos",
    english: "those",
    guess: "unquizzed",
    hint: "",
    id: "PXP371",
  },
  {
    spanish: "esas",
    english: "those",
    guess: "unquizzed",
    hint: "",
    id: "UYY742",
  },
  {
    spanish: "aquel",
    english: "that",
    guess: "unquizzed",
    hint: "",
    id: "BIK185",
  },
  {
    spanish: "aquella",
    english: "that",
    guess: "unquizzed",
    hint: "",
    id: "GMH766",
  },
  {
    spanish: "aquellos",
    english: "those",
    guess: "unquizzed",
    hint: "",
    id: "RAC098",
  },
  {
    spanish: "aquellas",
    english: "those",
    guess: "unquizzed",
    hint: "",
    id: "BML986",
  },
];
