export const Prepositions = [
  { spanish: "a", english: "to", guess: "unquizzed", hint: "", id: "AAC412" },
  {
    spanish: "antes",
    english: "before",
    guess: "unquizzed",
    hint: "",
    id: "LHA364",
  },
  {
    spanish: "debajo de",
    english: "under",
    guess: "unquizzed",
    hint: "",
    id: "XUS251",
  },
  {
    spanish: "junto a",
    english: "next to",
    guess: "unquizzed",
    hint: "",
    id: "FBG048",
  },
  {
    spanish: "con",
    english: "with",
    guess: "unquizzed",
    hint: "",
    id: "HPW972",
  },
  {
    spanish: "contra",
    english: "against",
    guess: "unquizzed",
    hint: "",
    id: "WYL086",
  },
  { spanish: "de", english: "of", guess: "unquizzed", hint: "", id: "XQK160" },
  {
    spanish: "desde",
    english: "from",
    guess: "unquizzed",
    hint: "",
    id: "IVS967",
  },
  {
    spanish: "originario de",
    english: "from",
    guess: "unquizzed",
    hint: "",
    id: "MNM378",
  },
  {
    spanish: "desde",
    english: "since",
    guess: "unquizzed",
    hint: "",
    id: "QXU250",
  },
  {
    spanish: "durante",
    english: "during",
    guess: "unquizzed",
    hint: "",
    id: "HCE823",
  },
  { spanish: "en", english: "in", guess: "unquizzed", hint: "", id: "IOH910" },
  { spanish: "en", english: "on", guess: "unquizzed", hint: "", id: "KYY965" },
  {
    spanish: "entre",
    english: "between",
    guess: "unquizzed",
    hint: "",
    id: "NHB425",
  },
  {
    spanish: "hacia",
    english: "towards",
    guess: "unquizzed",
    hint: "",
    id: "JUD923",
  },
  {
    spanish: "hasta",
    english: "until",
    guess: "unquizzed",
    hint: "",
    id: "FRG631",
  },
  {
    spanish: "por medio de",
    english: "by means of",
    guess: "unquizzed",
    hint: "",
    id: "XGM030",
  },
  {
    spanish: "para",
    english: "for",
    guess: "unquizzed",
    hint: "",
    id: "DAK903",
  },
  { spanish: "por", english: "by", guess: "unquizzed", hint: "", id: "KDT266" },
  {
    spanish: "por medio de",
    english: "through",
    guess: "unquizzed",
    hint: "",
    id: "XWR245",
  },
  {
    spanish: "según",
    english: "according to",
    guess: "unquizzed",
    hint: "",
    id: "XKK701",
  },
  {
    spanish: "sin",
    english: "without",
    guess: "unquizzed",
    hint: "",
    id: "BSK724",
  },
  { spanish: "en", english: "on", guess: "unquizzed", hint: "", id: "YRH237" },
  {
    spanish: "acerca de",
    english: "about",
    guess: "unquizzed",
    hint: "",
    id: "GVT857",
  },
  {
    spanish: "después",
    english: "after",
    guess: "unquizzed",
    hint: "",
    id: "JUA132",
  },
  {
    spanish: "detrás",
    english: "behind",
    guess: "unquizzed",
    hint: "",
    id: "KMW015",
  },
  {
    spanish: "a través de",
    english: "through",
    guess: "unquizzed",
    hint: "",
    id: "JWJ817",
  },
  {
    spanish: "cerca",
    english: "near",
    guess: "unquizzed",
    hint: "",
    id: "RCA424",
  },
  {
    spanish: "lejos de",
    english: "far from",
    guess: "unquizzed",
    hint: "",
    id: "WFX110",
  },
  {
    spanish: "debajo de",
    english: "under",
    guess: "unquizzed",
    hint: "",
    id: "JTC029",
  },
  {
    spanish: "encima de",
    english: "on top of",
    guess: "unquizzed",
    hint: "",
    id: "QDL430",
  },
  {
    spanish: "delante de",
    english: "in front of",
    guess: "unquizzed",
    hint: "",
    id: "WAD121",
  },
  {
    spanish: "detrás",
    english: "behind",
    guess: "unquizzed",
    hint: "",
    id: "YHC977",
  },
  {
    spanish: "junto a",
    english: "next to",
    guess: "unquizzed",
    hint: "",
    id: "HDF860",
  },
  {
    spanish: "delante de",
    english: "in front of",
    guess: "unquizzed",
    hint: "",
    id: "QSI612",
  },
  {
    spanish: "dentro",
    english: "inside",
    guess: "unquizzed",
    hint: "",
    id: "MIM389",
  },
  {
    spanish: "fuera de",
    english: "outside of",
    guess: "unquizzed",
    hint: "",
    id: "YWS524",
  },
  {
    spanish: "junto a",
    english: "next to",
    guess: "unquizzed",
    hint: "",
    id: "VPV400",
  },
  {
    spanish: "respecto a",
    english: "regarding",
    guess: "unquizzed",
    hint: "",
    id: "XWA051",
  },
  {
    spanish: "a pesar de",
    english: "despite",
    guess: "unquizzed",
    hint: "",
    id: "YCJ447",
  },
  {
    spanish: "alrededor",
    english: "around",
    guess: "unquizzed",
    hint: "",
    id: "AKB489",
  },
  {
    spanish: "antes",
    english: "before",
    guess: "unquizzed",
    hint: "",
    id: "WHP158",
  },
  {
    spanish: "después",
    english: "after",
    guess: "unquizzed",
    hint: "",
    id: "RPL240",
  },
  {
    spanish: "durante",
    english: "during",
    guess: "unquizzed",
    hint: "",
    id: "TIU134",
  },
  {
    spanish: "debido a",
    english: "because of",
    guess: "unquizzed",
    hint: "",
    id: "VHU687",
  },
  {
    spanish: "enfrentando",
    english: "facing",
    guess: "unquizzed",
    hint: "",
    id: "NXI004",
  },
  {
    spanish: "referente a",
    english: "regarding",
    guess: "unquizzed",
    hint: "",
    id: "ZRS370",
  },
  {
    spanish: "debido a",
    english: "due to",
    guess: "unquizzed",
    hint: "",
    id: "BAG006",
  },
  {
    spanish: "por causa de",
    english: "because of",
    guess: "unquizzed",
    hint: "",
    id: "GHV677",
  },
];
