export const Accessories = [
  {
    spanish: "elegante",
    english: "stylish",
    guess: "unquizzed",
    hint: "",
    id: "NRU370",
  },
  {
    spanish: "de moda",
    english: "trendy",
    guess: "unquizzed",
    hint: "",
    id: "ZMP123",
  },
  {
    spanish: "de moda",
    english: "fashionable",
    guess: "unquizzed",
    hint: "",
    id: "RDU933",
  },
  {
    spanish: "chic",
    english: "chic",
    guess: "unquizzed",
    hint: "",
    id: "YLS735",
  },
  {
    spanish: "clásico",
    english: "classic",
    guess: "unquizzed",
    hint: "",
    id: "FLP711",
  },
  {
    spanish: "moderno",
    english: "modern",
    guess: "unquizzed",
    hint: "",
    id: "DPF291",
  },
  {
    spanish: "vintage",
    english: "vintage",
    guess: "unquizzed",
    hint: "",
    id: "HRI003",
  },
  {
    spanish: "elegante",
    english: "elegant",
    guess: "unquizzed",
    hint: "",
    id: "FMA989",
  },
  {
    spanish: "sophisticated",
    english: "sophisticated",
    guess: "unquizzed",
    hint: "",
    id: "BHE638",
  },
  {
    spanish: "casual",
    english: "casual",
    guess: "unquizzed",
    hint: "",
    id: "HXR323",
  },
  {
    spanish: "formal",
    english: "formal",
    guess: "unquizzed",
    hint: "",
    id: "CHZ270",
  },
  {
    spanish: "funcional",
    english: "functional",
    guess: "unquizzed",
    hint: "",
    id: "VBO038",
  },
  {
    spanish: "versátil",
    english: "versatile",
    guess: "unquizzed",
    hint: "",
    id: "HCA289",
  },
  {
    spanish: "duradero",
    english: "durable",
    guess: "unquizzed",
    hint: "",
    id: "RJO273",
  },
  {
    spanish: "de lujo",
    english: "luxurious",
    guess: "unquizzed",
    hint: "",
    id: "VDT731",
  },
  {
    spanish: "atrevido",
    english: "edgy",
    guess: "unquizzed",
    hint: "",
    id: "HGV385",
  },
  {
    spanish: "retro",
    english: "retro",
    guess: "unquizzed",
    hint: "",
    id: "NCY318",
  },
  {
    spanish: "sin esfuerzo",
    english: "effortless",
    guess: "unquizzed",
    hint: "",
    id: "UPY261",
  },
  {
    spanish: "exquisito",
    english: "exquisite",
    guess: "unquizzed",
    hint: "",
    id: "HAM493",
  },
  {
    spanish: "bohemio",
    english: "bohemian",
    guess: "unquizzed",
    hint: "",
    id: "NFK399",
  },
  {
    spanish: "minimalista",
    english: "minimalist",
    guess: "unquizzed",
    hint: "",
    id: "JLI675",
  },
  {
    spanish: "recargado",
    english: "ornate",
    guess: "unquizzed",
    hint: "",
    id: "DYA978",
  },
  {
    spanish: "peculiar",
    english: "quirky",
    guess: "unquizzed",
    hint: "",
    id: "BWP081",
  },
  {
    spanish: "atemporal",
    english: "timeless",
    guess: "unquizzed",
    hint: "",
    id: "BVU230",
  },
  {
    spanish: "juguetón",
    english: "playful",
    guess: "unquizzed",
    hint: "",
    id: "GDQ553",
  },
  {
    spanish: "glamoroso",
    english: "glamorous",
    guess: "unquizzed",
    hint: "",
    id: "BUE946",
  },
  {
    spanish: "masculino",
    english: "masculine",
    guess: "unquizzed",
    hint: "",
    id: "IQD961",
  },
  {
    spanish: "femenino",
    english: "feminine",
    guess: "unquizzed",
    hint: "",
    id: "EYA139",
  },
];
