export const Accommodations = [
  {
    spanish: "lujoso",
    english: "luxurious",
    guess: "unquizzed",
    hint: "",
    id: "NKN490",
  },
  {
    spanish: "acogedor",
    english: "cozy",
    guess: "unquizzed",
    hint: "",
    id: "DBD435",
  },
  {
    spanish: "pintoresco",
    english: "quaint",
    guess: "unquizzed",
    hint: "",
    id: "VBL358",
  },
  {
    spanish: "rústico",
    english: "rustic",
    guess: "unquizzed",
    hint: "",
    id: "FPT746",
  },
  {
    spanish: "moderno",
    english: "modern",
    guess: "unquizzed",
    hint: "",
    id: "JQE253",
  },
  {
    spanish: "espacioso",
    english: "spacious",
    guess: "unquizzed",
    hint: "",
    id: "PYI413",
  },
  {
    spanish: "privado",
    english: "private",
    guess: "unquizzed",
    hint: "",
    id: "OUR750",
  },
  {
    spanish: "alejado",
    english: "secluded",
    guess: "unquizzed",
    hint: "",
    id: "ROZ916",
  },
  {
    spanish: "encantador",
    english: "charming",
    guess: "unquizzed",
    hint: "",
    id: "DGG355",
  },
  {
    spanish: "cómodo",
    english: "comfortable",
    guess: "unquizzed",
    hint: "",
    id: "GSN674",
  },
  {
    spanish: "elegante",
    english: "elegant",
    guess: "unquizzed",
    hint: "",
    id: "HBX545",
  },
  {
    spanish: "boutique",
    english: "boutique",
    guess: "unquizzed",
    hint: "",
    id: "SET972",
  },
  {
    spanish: "histórico",
    english: "historic",
    guess: "unquizzed",
    hint: "",
    id: "BPG527",
  },
  {
    spanish: "económico",
    english: "budget-friendly",
    guess: "unquizzed",
    hint: "",
    id: "EDK682",
  },
  {
    spanish: "pintoresco",
    english: "picturesque",
    guess: "unquizzed",
    hint: "",
    id: "PDR015",
  },
  {
    spanish: "amigable para la familia",
    english: "family-friendly",
    guess: "unquizzed",
    hint: "",
    id: "QRG289",
  },
  {
    spanish: "elegante",
    english: "stylish",
    guess: "unquizzed",
    hint: "",
    id: "PST313",
  },
  {
    spanish: "frente a la playa",
    english: "beachfront",
    guess: "unquizzed",
    hint: "",
    id: "WKS959",
  },
  {
    spanish: "montañoso",
    english: "mountainous",
    guess: "unquizzed",
    hint: "",
    id: "OYK770",
  },
  {
    spanish: "conveniente",
    english: "convenient",
    guess: "unquizzed",
    hint: "",
    id: "BTX119",
  },
  {
    spanish: "amigable con las mascotas",
    english: "pet-friendly",
    guess: "unquizzed",
    hint: "",
    id: "PIW295",
  },
  {
    spanish: "todo incluido",
    english: "all-inclusive",
    guess: "unquizzed",
    hint: "",
    id: "BHY332",
  },
  {
    spanish: "romántico",
    english: "romantic",
    guess: "unquizzed",
    hint: "",
    id: "AVN076",
  },
  {
    spanish: "tradicional",
    english: "traditional",
    guess: "unquizzed",
    hint: "",
    id: "IFV534",
  },
  {
    spanish: "único",
    english: "unique",
    guess: "unquizzed",
    hint: "",
    id: "CQG023",
  },
  {
    spanish: "amueblado",
    english: "furnished",
    guess: "unquizzed",
    hint: "",
    id: "SRW854",
  },
  {
    spanish: "acogedor",
    english: "cosy",
    guess: "unquizzed",
    hint: "",
    id: "KOH996",
  },
  {
    spanish: "sereno",
    english: "serene",
    guess: "unquizzed",
    hint: "",
    id: "OBN897",
  },
  {
    spanish: "pacífico",
    english: "peaceful",
    guess: "unquizzed",
    hint: "",
    id: "HUZ597",
  },
  {
    spanish: "accesible",
    english: "accessible",
    guess: "unquizzed",
    hint: "",
    id: "IHZ529",
  },
  {
    spanish: "de moda",
    english: "trendy",
    guess: "unquizzed",
    hint: "",
    id: "FQG734",
  },
  {
    spanish: "sostenible",
    english: "sustainable",
    guess: "unquizzed",
    hint: "",
    id: "XIQ252",
  },
  {
    spanish: "bien equipado",
    english: "well-appointed",
    guess: "unquizzed",
    hint: "",
    id: "UWC138",
  },
  {
    spanish: "panorámico",
    english: "panoramic",
    guess: "unquizzed",
    hint: "",
    id: "OSY272",
  },
  {
    spanish: "estiloso",
    english: "stylish",
    guess: "unquizzed",
    hint: "",
    id: "ETU848",
  },
  {
    spanish: "contemporáneo",
    english: "contemporary",
    guess: "unquizzed",
    hint: "",
    id: "ZHV096",
  },
  {
    spanish: "extravagante",
    english: "extravagant",
    guess: "unquizzed",
    hint: "",
    id: "MHZ985",
  },
  {
    spanish: "íntimo",
    english: "intimate",
    guess: "unquizzed",
    hint: "",
    id: "HXR737",
  },
  {
    spanish: "vibrante",
    english: "vibrant",
    guess: "unquizzed",
    hint: "",
    id: "HFN152",
  },
  {
    spanish: "zen",
    english: "zen",
    guess: "unquizzed",
    hint: "",
    id: "OTM327",
  },
  {
    spanish: "innovador",
    english: "innovative",
    guess: "unquizzed",
    hint: "",
    id: "OYT377",
  },
  {
    spanish: "de alta gama",
    english: "high-end",
    guess: "unquizzed",
    hint: "",
    id: "APU841",
  },
];
