export const WeatherAndClimate = [
  {
    spanish: "soleado",
    english: "sunny",
    guess: "unquizzed",
    hint: "",
    id: "SCO827",
  },
  {
    spanish: "nublado",
    english: "cloudy",
    guess: "unquizzed",
    hint: "",
    id: "YNY044",
  },
  {
    spanish: "lluvioso",
    english: "rainy",
    guess: "unquizzed",
    hint: "",
    id: "QBF436",
  },
  {
    spanish: "tormentoso",
    english: "stormy",
    guess: "unquizzed",
    hint: "",
    id: "SNP180",
  },
  {
    spanish: "ventoso",
    english: "windy",
    guess: "unquizzed",
    hint: "",
    id: "WBP043",
  },
  {
    spanish: "nevado",
    english: "snowy",
    guess: "unquizzed",
    hint: "",
    id: "NZQ671",
  },
  {
    spanish: "neblinoso",
    english: "foggy",
    guess: "unquizzed",
    hint: "",
    id: "BDN835",
  },
  {
    spanish: "brumoso",
    english: "hazy",
    guess: "unquizzed",
    hint: "",
    id: "KRT693",
  },
  {
    spanish: "nublado",
    english: "overcast",
    guess: "unquizzed",
    hint: "",
    id: "DEO091",
  },
  {
    spanish: "despejado",
    english: "clear",
    guess: "unquizzed",
    hint: "",
    id: "NGP581",
  },
  {
    spanish: "húmedo",
    english: "humid",
    guess: "unquizzed",
    hint: "",
    id: "SND994",
  },
  {
    spanish: "seco",
    english: "dry",
    guess: "unquizzed",
    hint: "",
    id: "BEU312",
  },
  {
    spanish: "húmedo",
    english: "damp",
    guess: "unquizzed",
    hint: "",
    id: "YKZ229",
  },
  {
    spanish: "bochornoso",
    english: "muggy",
    guess: "unquizzed",
    hint: "",
    id: "NGX788",
  },
  {
    spanish: "ventoso",
    english: "breezy",
    guess: "unquizzed",
    hint: "",
    id: "TVO979",
  },
  {
    spanish: "fresco",
    english: "chilly",
    guess: "unquizzed",
    hint: "",
    id: "CXN577",
  },
  {
    spanish: "caluroso",
    english: "hot",
    guess: "unquizzed",
    hint: "",
    id: "IIO257",
  },
  {
    spanish: "templado",
    english: "warm",
    guess: "unquizzed",
    hint: "",
    id: "UEM217",
  },
  {
    spanish: "fresco",
    english: "cool",
    guess: "unquizzed",
    hint: "",
    id: "WXM452",
  },
  {
    spanish: "helado",
    english: "freezing",
    guess: "unquizzed",
    hint: "",
    id: "YCM398",
  },
  {
    spanish: "ventoso",
    english: "blustery",
    guess: "unquizzed",
    hint: "",
    id: "IIT548",
  },
  {
    spanish: "templado",
    english: "mild",
    guess: "unquizzed",
    hint: "",
    id: "DUP350",
  },
  {
    spanish: "sombrío",
    english: "gloomy",
    guess: "unquizzed",
    hint: "",
    id: "SAT696",
  },
  {
    spanish: "turbulento",
    english: "thunderous",
    guess: "unquizzed",
    hint: "",
    id: "YHM291",
  },
  {
    spanish: "torrencial",
    english: "torrential",
    guess: "unquizzed",
    hint: "",
    id: "QUJ532",
  },
  {
    spanish: "lloviznoso",
    english: "drizzly",
    guess: "unquizzed",
    hint: "",
    id: "QSH251",
  },
];
