export const Beverages = [
  { spanish: "fresco", english: "refreshing" },
  { spanish: "dulce", english: "sweet" },
  { spanish: "amargo", english: "bitter" },
  { spanish: "fuerte", english: "strong" },
  { spanish: "suave", english: "mild" },
  { spanish: "sabroso", english: "flavorful" },
  { spanish: "agrio", english: "tangy" },
  { spanish: "suave", english: "smooth" },
  { spanish: "cremoso", english: "creamy" },
  { spanish: "helado", english: "icy" },
  { spanish: "caliente", english: "hot" },
  { spanish: "frío", english: "cold" },
  { spanish: "agrio", english: "sour" },
  { spanish: "salado", english: "salty" },
  { spanish: "picante", english: "spicy" },
  { spanish: "crujiente", english: "crisp" },
  { spanish: "efervescente", english: "fizzy" },
  { spanish: "tibio", english: "warm" },
  { spanish: "rico", english: "rich" },
  { spanish: "aromático", english: "aromatic" },
  { spanish: "burbujeante", english: "bubbly" },
  { spanish: "con cafeína", english: "caffeinated" },
  { spanish: "descafeinado", english: "decaffeinated" },
  { spanish: "vivaz", english: "brisk" },
  { spanish: "espumoso", english: "frothy" },
  { spanish: "robusto", english: "robust" },
  { spanish: "débil", english: "weak" },
  { spanish: "a nuez", english: "nutty" },
  { spanish: "terroso", english: "earthy" },
  { spanish: "delicioso", english: "luscious" },
  { spanish: "afrutado", english: "fruity" },
  { spanish: "chispeante", english: "sparkling" },
];
