export const HobbiesAndInterests = [
  { spanish: "activo", english: "active " },
  { spanish: "atlético", english: "athletic " },
  { spanish: "competitivo", english: "competitive " },
  { spanish: "creativo", english: "creative " },
  { spanish: "energético", english: "energetic " },
  { spanish: "entretenido", english: "entertaining " },
  { spanish: "emocionante", english: "exciting " },
  { spanish: "satisfactorio", english: "fulfilling " },
  { spanish: "divertido", english: "fun " },
  { spanish: "saludable", english: "healthy " },
  { spanish: "recreativo", english: "leisurely " },
  { spanish: "meditativo", english: "meditative " },
  { spanish: "al aire libre", english: "outdoor " },
  { spanish: "pacífico", english: "peaceful " },
  { spanish: "relajante", english: "relaxing " },
  { spanish: "gratificante", english: "rewarding " },
  { spanish: "satisfactorio", english: "satisfying " },
  { spanish: "social", english: "social " },
  { spanish: "estimulante", english: "stimulating " },
  { spanish: "terapéutico", english: "therapeutic " },
];
