export const MediaTypes = [
  { spanish: "entretenido", english: "entertaining" },
  { spanish: "cautivador", english: "captivating" },
  { spanish: "atractivo", english: "engaging" },
  { spanish: "inspirador", english: "inspiring" },
  { spanish: "educativo", english: "educational" },
  { spanish: "conmovedor", english: "heartwarming" },
  { spanish: "emocionante", english: "emotional" },
  { spanish: "provocador de pensamientos", english: "thought-provoking" },
  { spanish: "suspense", english: "suspenseful" },
  { spanish: "emocionante", english: "thrilling" },
  { spanish: "edificante", english: "uplifting" },
  { spanish: "informativo", english: "informative" },
  { spanish: "persuasivo", english: "persuasive" },
  { spanish: "impactante", english: "impactful" },
  { spanish: "informativo", english: "informative" },
  { spanish: "creativo", english: "creative" },
  { spanish: "gracioso", english: "funny" },
  { spanish: "edificante", english: "uplifting" },
  { spanish: "interesante", english: "interesting" },
  { spanish: "innovador", english: "innovative" },
];
