export const nonVerbalCommunication = [
  "gesturing",
  "pointing",
  "shrugging",
  "waving",
  "signaling",
  "making eye contact",
  "frowning",
  "smiling",
  "winking",
  "clapping",
  "hugging",
  "handshaking",
  "high-fiving",
  "blinking",
  "saluting",
  "bowing",
  "sneering",
  "rolling eyes",
  "sighing",
  "whistling",
  "wincing",
  "waving goodbye",
  "waving hello",
  "pouting",
  "thumbs up",
  "thumbs down",
  "flipping the bird",
  "air quotes",
  "crossing arms",
  "patting on the back",
  "kissing",
  "nudging",
  "punching",
  "holding hands",
  "fist bumping",
  "shaking head",
  "nodding",
  "blowing kisses",
  "giving a thumbs up",
  "giving a thumbs down",
  "giving a high-five",
  "giving a round of applause",
  "raising eyebrows",
  "giving a wink",
  "staring",
  "giving a salute",
];
