export const ArtForms = [
  {
    spanish: "pintura",
    english: "painting",
    guess: "unquizzed",
    hint: "",
    id: "TIC333",
  },
  {
    spanish: "escultura",
    english: "sculpture",
    guess: "unquizzed",
    hint: "",
    id: "EHC650",
  },
  {
    spanish: "dibujo",
    english: "drawing",
    guess: "unquizzed",
    hint: "",
    id: "KTM322",
  },
  {
    spanish: "fotografía",
    english: "photography",
    guess: "unquizzed",
    hint: "",
    id: "RHU872",
  },
  {
    spanish: "grabado",
    english: "printmaking",
    guess: "unquizzed",
    hint: "",
    id: "TUS920",
  },
  {
    spanish: "collage",
    english: "collage",
    guess: "unquizzed",
    hint: "",
    id: "RWA158",
  },
  {
    spanish: "cerámica",
    english: "pottery",
    guess: "unquizzed",
    hint: "",
    id: "BFZ653",
  },
  {
    spanish: "cerámica",
    english: "ceramics",
    guess: "unquizzed",
    hint: "",
    id: "SDM773",
  },
  {
    spanish: "escultura en madera",
    english: "carving",
    guess: "unquizzed",
    hint: "",
    id: "BTJ810",
  },
  {
    spanish: "grabado",
    english: "engraving",
    guess: "unquizzed",
    hint: "",
    id: "NAO886",
  },
  {
    spanish: "aguafuerte",
    english: "etching",
    guess: "unquizzed",
    hint: "",
    id: "MIL149",
  },
  {
    spanish: "xilografía",
    english: "woodcut",
    guess: "unquizzed",
    hint: "",
    id: "CKJ477",
  },
  {
    spanish: "instalación",
    english: "installation",
    guess: "unquizzed",
    hint: "",
    id: "ONE615",
  },
  {
    spanish: "performance",
    english: "performance",
    guess: "unquizzed",
    hint: "",
    id: "EBB047",
  },
  {
    spanish: "danza",
    english: "dance",
    guess: "unquizzed",
    hint: "",
    id: "AON156",
  },
  {
    spanish: "teatro",
    english: "theater",
    guess: "unquizzed",
    hint: "",
    id: "KEQ405",
  },
  {
    spanish: "cine",
    english: "film",
    guess: "unquizzed",
    hint: "",
    id: "YBG334",
  },
  {
    spanish: "música",
    english: "music",
    guess: "unquizzed",
    hint: "",
    id: "HXR873",
  },
  {
    spanish: "literatura",
    english: "literature",
    guess: "unquizzed",
    hint: "",
    id: "ZNS320",
  },
  {
    spanish: "poesía",
    english: "poetry",
    guess: "unquizzed",
    hint: "",
    id: "CBR899",
  },
  {
    spanish: "prosa",
    english: "prose",
    guess: "unquizzed",
    hint: "",
    id: "DAF802",
  },
  {
    spanish: "novela",
    english: "novel",
    guess: "unquizzed",
    hint: "",
    id: "KDW925",
  },
  {
    spanish: "cuento",
    english: "short story",
    guess: "unquizzed",
    hint: "",
    id: "EBI884",
  },
  {
    spanish: "obra de teatro",
    english: "play",
    guess: "unquizzed",
    hint: "",
    id: "OXT096",
  },
  {
    spanish: "novela",
    english: "novel",
    guess: "unquizzed",
    hint: "",
    id: "BEI964",
  },
  {
    spanish: "biografía",
    english: "biography",
    guess: "unquizzed",
    hint: "",
    id: "UYO671",
  },
  {
    spanish: "autobiografía",
    english: "autobiography",
    guess: "unquizzed",
    hint: "",
    id: "OML266",
  },
  {
    spanish: "ensayo",
    english: "essay",
    guess: "unquizzed",
    hint: "",
    id: "RKA447",
  },
  {
    spanish: "artículo",
    english: "article",
    guess: "unquizzed",
    hint: "",
    id: "OCB351",
  },
  {
    spanish: "crítica",
    english: "critique",
    guess: "unquizzed",
    hint: "",
    id: "LWZ552",
  },
  {
    spanish: "periodismo",
    english: "journalism",
    guess: "unquizzed",
    hint: "",
    id: "GJC002",
  },
];
