export const famousWorksAndAuthors = [
  "iconic",
  "prolific",
  "masterful",
  "literary",
  "classic",
  "acclaimed",
  "decorated",
  "legendary",
  "groundbreaking",
  "innovative",
  "seminal",
  "remarkable",
  "timeless",
  "seminal",
  "influential",
  "renowned",
  "profound",
  "captivating",
  "profound",
  "epic",
  "famous",
  "rare",
  "critically acclaimed",
  "critically acclaimed",
  "award-winning",
  "prolific",
  "brilliant",
  "creative",
  "imaginative",
  "multi-award-winning",
];
