const EGuessedCorrectly = {
  UNQUIZZED: "unquizzed",
  CORRECT: "correct",
  INCORRECT: "incorrect",
};

var flashCardsSets = [
  {
    thumbnail: "https://picsum.photos/200/300",
    title: "Common Phrases",
    id: "common_phrases",
    cards: [
      {
        front: "adiós",
        back: "goodbye",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 1,
      },
      {
        front: "gracias",
        back: "thank you",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 2,
      },
      {
        front: "buenos días",
        back: "good morning",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 3,
      },
      {
        front: "buenas noches",
        back: "good night",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 4,
      },
      {
        front: "mucho gusto",
        back: "nice to meet you",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 5,
      },
      {
        front: "sí",
        back: "yes",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 6,
      },
      {
        front: "no",
        back: "no",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 7,
      },
      {
        front: "perdón",
        back: "excuse me",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 8,
      },
      {
        front: "por favor",
        back: "please",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 9,
      },
      {
        front: "de nada",
        back: "you're welcome",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 10,
      },
      {
        front: "lo siento",
        back: "sorry",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 11,
      },
      {
        front: "hablo",
        back: "I speak",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 12,
      },
      {
        front: "hablas",
        back: "you speak",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 13,
      },
      {
        front: "español",
        back: "Spanish",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 14,
      },
      {
        front: "inglés",
        back: "English",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 15,
      },
      {
        front: "disculpe",
        back: "excuse me",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 16,
      },
      {
        front: "hola",
        back: "hello",
        hint: "",
        guess: EGuessedCorrectly.UNQUIZZED,
        id: 17,
      },
    ],
  },
];
