export const pronouns = [
  { front: "yo", back: "I", guess: "unquizzed", hint: "", id: "YJC358" },
  {
    front: "tú",
    back: "you",
    notes: "informal singular",
    guess: "unquizzed",
    hint: "",
    id: "MZA846",
  },
  {
    front: "usted",
    back: "you",
    notes: "formal singular",
    guess: "unquizzed",
    hint: "",
    id: "ZYM649",
  },
  { front: "él", back: "he", guess: "unquizzed", hint: "", id: "GJL377" },
  { front: "ella", back: "she", guess: "unquizzed", hint: "", id: "EGS055" },
  {
    front: "nosotros",
    back: "we",
    notes: "masculine or mixed group",
    guess: "unquizzed",
    hint: "",
    id: "XEZ824",
  },
  {
    front: "nosotras",
    back: "we",
    notes: "feminine",
    guess: "unquizzed",
    hint: "",
    id: "CBJ287",
  },
  {
    front: "vosotros",
    back: "you all",
    notes: "informal masculine or mixed group",
    guess: "unquizzed",
    hint: "",
    id: "DAQ360",
  },
  {
    front: "vosotras",
    back: "you all",
    notes: "informal feminine",
    guess: "unquizzed",
    hint: "",
    id: "VZG425",
  },
  {
    front: "ustedes",
    back: "you all",
    notes: "formal",
    guess: "unquizzed",
    hint: "",
    id: "RTI471",
  },
  {
    front: "ellos",
    back: "they",
    notes: "masculine or mixed group",
    guess: "unquizzed",
    hint: "",
    id: "XEG747",
  },
  {
    front: "ellas",
    back: "they",
    notes: "feminine",
    guess: "unquizzed",
    hint: "",
    id: "AGD770",
  },
  {
    front: "mío",
    back: "mine",
    notes: "masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "TRQ949",
  },
  {
    front: "mía",
    back: "mine",
    notes: "feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "LCP209",
  },
  {
    front: "míos",
    back: "mine",
    notes: "masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "MNI154",
  },
  {
    front: "mías",
    back: "mine",
    notes: "feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "QOG219",
  },
  {
    front: "tuyo",
    back: "yours",
    notes: "informal masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "DNX201",
  },
  {
    front: "tuya",
    back: "yours",
    notes: "informal feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "IFY914",
  },
  {
    front: "tuyos",
    back: "yours",
    notes: "informal masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "AXP937",
  },
  {
    front: "tuyas",
    back: "yours",
    notes: "informal feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "TGQ126",
  },
  {
    front: "suyo",
    back: "his/hers/yours",
    notes: "formal masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "IYO507",
  },
  {
    front: "suya",
    back: "his/hers/yours",
    notes: "formal feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "OOA959",
  },
  {
    front: "suyos",
    back: "his/hers/yours",
    notes: "formal masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "GVI343",
  },
  {
    front: "suyas",
    back: "his/hers/yours",
    notes: "formal feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "JBV254",
  },
  {
    front: "nuestro",
    back: "ours",
    notes: "masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "OBV909",
  },
  {
    front: "nuestra",
    back: "ours",
    notes: "feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "VOS946",
  },
  {
    front: "nuestros",
    back: "ours",
    notes: "masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "FEM960",
  },
  {
    front: "nuestras",
    back: "ours",
    notes: "feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "XUY925",
  },
  {
    front: "vuestro",
    back: "yours",
    notes: "informal plural masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "WON180",
  },
  {
    front: "vuestra",
    back: "yours",
    notes: "informal plural feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "NOB582",
  },
  {
    front: "vuestros",
    back: "yours",
    notes: "informal plural masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "RXU079",
  },
  {
    front: "vuestras",
    back: "yours",
    notes: "informal plural feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "UGK404",
  },
  { front: "me", back: "myself", guess: "unquizzed", hint: "", id: "GXM951" },
  {
    front: "te",
    back: "yourself",
    notes: "informal",
    guess: "unquizzed",
    hint: "",
    id: "HDV430",
  },
  {
    front: "se",
    back: "himself/herself/yourself",
    notes: "formal",
    guess: "unquizzed",
    hint: "",
    id: "DOF951",
  },
  {
    front: "nos",
    back: "ourselves",
    guess: "unquizzed",
    hint: "",
    id: "FQP026",
  },
  {
    front: "os",
    back: "yourselves",
    notes: "informal plural",
    guess: "unquizzed",
    hint: "",
    id: "ZYK591",
  },
  {
    front: "se",
    back: "themselves/yourselves",
    notes: "formal plural",
    guess: "unquizzed",
    hint: "",
    id: "QRT715",
  },
  { front: "me", back: "me", guess: "unquizzed", hint: "", id: "ADW975" },
  {
    front: "te",
    back: "you",
    notes: "informal",
    guess: "unquizzed",
    hint: "",
    id: "EVJ446",
  },
  {
    front: "lo",
    back: "him/it",
    notes: "masculine",
    guess: "unquizzed",
    hint: "",
    id: "BVJ748",
  },
  {
    front: "la",
    back: "her/it",
    notes: "feminine",
    guess: "unquizzed",
    hint: "",
    id: "UPH447",
  },
  { front: "nos", back: "us", guess: "unquizzed", hint: "", id: "QPT469" },
  {
    front: "os",
    back: "you all",
    notes: "informal",
    guess: "unquizzed",
    hint: "",
    id: "UTW594",
  },
  {
    front: "los",
    back: "them",
    notes: "masculine",
    guess: "unquizzed",
    hint: "",
    id: "SKI677",
  },
  {
    front: "las",
    back: "them",
    notes: "feminine",
    guess: "unquizzed",
    hint: "",
    id: "KKD564",
  },
  {
    front: "me",
    back: "to/for me",
    guess: "unquizzed",
    hint: "",
    id: "RGE338",
  },
  {
    front: "te",
    back: "to/for you",
    notes: "informal",
    guess: "unquizzed",
    hint: "",
    id: "LVY730",
  },
  {
    front: "le",
    back: "to/for him/her/you",
    notes: "formal",
    guess: "unquizzed",
    hint: "",
    id: "BPT329",
  },
  {
    front: "nos",
    back: "to/for us",
    guess: "unquizzed",
    hint: "",
    id: "HFF853",
  },
  {
    front: "os",
    back: "to/for you all",
    notes: "informal",
    guess: "unquizzed",
    hint: "",
    id: "AQL707",
  },
  {
    front: "les",
    back: "to/for them/you all",
    notes: "formal",
    guess: "unquizzed",
    hint: "",
    id: "FMR245",
  },
  {
    front: "este",
    back: "this",
    notes: "masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "XGK714",
  },
  {
    front: "esta",
    back: "this",
    notes: "feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "GBO405",
  },
  {
    front: "estos",
    back: "these",
    notes: "masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "LST958",
  },
  {
    front: "estas",
    back: "these",
    notes: "feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "FNN355",
  },
  {
    front: "ese",
    back: "that",
    notes: "masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "WNJ414",
  },
  {
    front: "esa",
    back: "that",
    notes: "feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "TMM015",
  },
  {
    front: "esos",
    back: "those",
    notes: "masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "RGL727",
  },
  {
    front: "esas",
    back: "those",
    notes: "feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "UPH285",
  },
  {
    front: "aquel",
    back: "that",
    notes: "over there, masculine singular",
    guess: "unquizzed",
    hint: "",
    id: "BRS410",
  },
  {
    front: "aquella",
    back: "that",
    notes: "over there, feminine singular",
    guess: "unquizzed",
    hint: "",
    id: "HWD726",
  },
  {
    front: "aquellos",
    back: "those",
    notes: "over there, masculine plural",
    guess: "unquizzed",
    hint: "",
    id: "PIF978",
  },
  {
    front: "aquellas",
    back: "those",
    notes: "over there, feminine plural",
    guess: "unquizzed",
    hint: "",
    id: "DNT421",
  },
];
