export const AdverbsOfDoubt = [
  { spanish: "tal vez", english: "maybe" },
  { spanish: "quizás", english: "perhaps" },
  { spanish: "posiblemente", english: "possibly" },
  { spanish: "probablemente", english: "probably" },
  { spanish: "aparentemente", english: "apparently" },
  { spanish: "dudosamente", english: "doubtfully" },
  { spanish: "presumiblemente", english: "presumably" },
  { spanish: "concebiblemente", english: "conceivably" },
  { spanish: "supuestamente", english: "supposedly" },
  { spanish: "cuestionablemente", english: "questionably" },
  { spanish: "aparentemente", english: "seemingly" },
  { spanish: "discutiblemente", english: "arguably" },
  { spanish: "discutiblemente", english: "debatably" },
  { spanish: "presumiblemente", english: "suspectedly" },
  { spanish: "presuntivamente", english: "putatively" },
  { spanish: "ostensiblemente", english: "ostensibly" },
  { spanish: "admitidamente", english: "admittedly" },
  { spanish: "supuestamente", english: "allegedly" },
];
