export const Transport = [
  { spanish: "caminar", english: "walk" },
  { spanish: "correr", english: "run" },
  { spanish: "trote", english: "jog" },
  { spanish: "correr", english: "sprint" },
  { spanish: "caminata", english: "hike" },
  { spanish: "paseo", english: "stroll" },
  { spanish: "marchar", english: "march" },
  { spanish: "pasear", english: "amble" },
  { spanish: "caminar", english: "saunter" },
  { spanish: "travesía", english: "trek" },
  { spanish: "deambular", english: "wander" },
  { spanish: "vagar", english: "roam" },
  { spanish: "trote", english: "trot" },
  { spanish: "galopar", english: "gallop" },
  { spanish: "competir", english: "race" },
  { spanish: "viajar", english: "travel" },
  { spanish: "viajar diariamente", english: "commute" },
  { spanish: "ciclismo", english: "cycle" },
  { spanish: "andar en bicicleta", english: "bike" },
  { spanish: "paseo", english: "ride" },
  { spanish: "manejar", english: "drive" },
  { spanish: "navegar", english: "cruise" },
  { spanish: "navegar a vela", english: "sail" },
  { spanish: "volar", english: "fly" },
  { spanish: "patinar", english: "skate" },
  { spanish: "esquiar", english: "ski" },
  { spanish: "deslizarse", english: "glide" },
  { spanish: "patinar en tabla", english: "skateboard" },
  { spanish: "deslizarse", english: "scoot" },
  { spanish: "patineta", english: "scooter" },
  { spanish: "derrapar", english: "skid" },
  { spanish: "resbalar", english: "slide" },
  { spanish: "columpiarse", english: "swing" },
  { spanish: "balancearse", english: "swing" },
  { spanish: "jalar", english: "pull" },
  { spanish: "arrastrar", english: "drag" },
  { spanish: "empujar", english: "push" },
  { spanish: "remolcar", english: "tow" },
  { spanish: "cargar", english: "carry" },
  { spanish: "transportar", english: "transport" },
  { spanish: "enviar", english: "ship" },
  { spanish: "flotar", english: "hover" },
  { spanish: "cojear", english: "hobble" },
  { spanish: "arrastrarse", english: "crawl" },
  { spanish: "arrastrarse", english: "creep" },
  { spanish: "nadar", english: "swim" },
  { spanish: "bucear", english: "dive" },
  { spanish: "brincar", english: "jump" },
  { spanish: "saltar", english: "leap" },
  { spanish: "brincar", english: "hop" },
  { spanish: "brincar", english: "skip" },
  { spanish: "botar", english: "bounce" },
  { spanish: "saltar", english: "bound" },
  { spanish: "saltar", english: "spring" },
  { spanish: "caer", english: "fall" },
  { spanish: "descender", english: "descend" },
  { spanish: "subir", english: "climb" },
  { spanish: "ascender", english: "ascend" },
  { spanish: "escalar", english: "scale" },
  { spanish: "agacharse", english: "stoop" },
  { spanish: "trepar", english: "clamber" },
  { spanish: "escalar laboriosamente", english: "scramble" },
  { spanish: "caerse", english: "cramble" },
  { spanish: "tropiezo", english: "tumble" },
  { spanish: "rodar", english: "roll" },
  { spanish: "deslizar", english: "slide" },
  { spanish: "resbalar", english: "slip" },
  { spanish: "pisar", english: "tread" },
  { spanish: "caminar de puntillas", english: "tiptoe" },
  { spanish: "estampar", english: "stamp" },
  { spanish: "arrancar", english: "strut" },
  { spanish: "cojear", english: "limp" },
  { spanish: "vadear", english: "wade" },
  { spanish: "apechugar", english: "slog" },
  { spanish: "marchar pesadamente", english: "trudge" },
  { spanish: "avanzar pesadamente", english: "plod" },
  { spanish: "pasear", english: "mosey" },
  { spanish: "remar", english: "paddle" },
  { spanish: "remar", english: "row" },
  { spanish: "pilotar", english: "pilot" },
  { spanish: "manejar", english: "drive" },
  { spanish: "manejar", english: "steer" },
  { spanish: "navegar", english: "navigate" },
  { spanish: "guiar", english: "guide" },
];
