export const Accessories = [
  { spa: "elegante", eng: "stylish", hint: "", id: "VVD569" },
  { spa: "de moda", eng: "trendy", hint: "", id: "PLJ243" },
  { spa: "de moda", eng: "fashionable", hint: "", id: "VUZ001" },
  { spa: "chic", eng: "chic", hint: "", id: "MFM390" },
  { spa: "clásico", eng: "classic", hint: "", id: "WUJ940" },
  { spa: "moderno", eng: "modern", hint: "", id: "YUL479" },
  { spa: "vintage", eng: "vintage", hint: "", id: "QUY682" },
  { spa: "elegante", eng: "elegant", hint: "", id: "PWJ378" },
  {
    spa: "sophisticated",
    eng: "sophisticated",
    hint: "",
    id: "LJL837",
  },
  { spa: "casual", eng: "casual", hint: "", id: "LVW362" },
  { spa: "formal", eng: "formal", hint: "", id: "FXI015" },
  { spa: "funcional", eng: "functional", hint: "", id: "NWY110" },
  { spa: "versátil", eng: "versatile", hint: "", id: "EUS126" },
  { spa: "duradero", eng: "durable", hint: "", id: "PMR106" },
  { spa: "de lujo", eng: "luxurious", hint: "", id: "GOT766" },
  { spa: "atrevido", eng: "edgy", hint: "", id: "ZTF410" },
  { spa: "retro", eng: "retro", hint: "", id: "QCF334" },
  { spa: "sin esfuerzo", eng: "effortless", hint: "", id: "PWJ831" },
  { spa: "exquisito", eng: "exquisite", hint: "", id: "JJK298" },
  { spa: "bohemio", eng: "bohemian", hint: "", id: "KRR638" },
  { spa: "minimalista", eng: "minimalist", hint: "", id: "ACS141" },
  { spa: "recargado", eng: "ornate", hint: "", id: "CGB986" },
  { spa: "peculiar", eng: "quirky", hint: "", id: "FCX007" },
  { spa: "atemporal", eng: "timeless", hint: "", id: "KSC373" },
  { spa: "juguetón", eng: "playful", hint: "", id: "EAO547" },
  { spa: "glamoroso", eng: "glamorous", hint: "", id: "CJN753" },
  { spa: "masculino", eng: "masculine", hint: "", id: "VHV433" },
  { spa: "femenino", eng: "feminine", hint: "", id: "AFN679" },
];
