export const Accommodations = [
  { spanish: "lujoso", eng: "luxurious", hint: "", id: "GXC459" },
  { spanish: "acogedor", eng: "cozy", hint: "", id: "ROR629" },
  { spanish: "pintoresco", eng: "quaint", hint: "", id: "TFC549" },
  { spanish: "rústico", eng: "rustic", hint: "", id: "RQJ482" },
  { spanish: "moderno", eng: "modern", hint: "", id: "EWC979" },
  { spanish: "espacioso", eng: "spacious", hint: "", id: "HUE914" },
  { spanish: "privado", eng: "private", hint: "", id: "RSV967" },
  { spanish: "alejado", eng: "secluded", hint: "", id: "CXR983" },
  { spanish: "encantador", eng: "charming", hint: "", id: "JRC776" },
  { spanish: "cómodo", eng: "comfortable", hint: "", id: "GPG886" },
  { spanish: "elegante", eng: "elegant", hint: "", id: "XTJ437" },
  { spanish: "boutique", eng: "boutique", hint: "", id: "GOZ840" },
  { spanish: "histórico", eng: "historic", hint: "", id: "CNA531" },
  { spanish: "económico", eng: "budget-friendly", hint: "", id: "SUW142" },
  { spanish: "pintoresco", eng: "picturesque", hint: "", id: "WQN560" },
  {
    spanish: "amigable para la familia",
    eng: "family-friendly",
    hint: "",
    id: "JCL796",
  },
  { spanish: "elegante", eng: "stylish", hint: "", id: "QOZ977" },
  {
    spanish: "frente a la playa",
    eng: "beachfront",
    hint: "",
    id: "DQQ785",
  },
  { spanish: "montañoso", eng: "mountainous", hint: "", id: "IBI194" },
  { spanish: "conveniente", eng: "convenient", hint: "", id: "NGT155" },
  {
    spanish: "amigable con las mascotas",
    eng: "pet-friendly",
    hint: "",
    id: "RIC974",
  },
  {
    spanish: "todo incluido",
    eng: "all-inclusive",
    hint: "",
    id: "QOV683",
  },
  { spanish: "romántico", eng: "romantic", hint: "", id: "RIT099" },
  { spanish: "tradicional", eng: "traditional", hint: "", id: "DOB550" },
  { spanish: "único", eng: "unique", hint: "", id: "DED139" },
  { spanish: "amueblado", eng: "furnished", hint: "", id: "RQR134" },
  { spanish: "acogedor", eng: "cosy", hint: "", id: "BDR328" },
  { spanish: "sereno", eng: "serene", hint: "", id: "FHN689" },
  { spanish: "pacífico", eng: "peaceful", hint: "", id: "NRZ071" },
  { spanish: "accesible", eng: "accessible", hint: "", id: "IID939" },
  { spanish: "de moda", eng: "trendy", hint: "", id: "NRU865" },
  { spanish: "sostenible", eng: "sustainable", hint: "", id: "IUA719" },
  {
    spanish: "bien equipado",
    eng: "well-appointed",
    hint: "",
    id: "EXZ685",
  },
  { spanish: "panorámico", eng: "panoramic", hint: "", id: "DIG489" },
  { spanish: "estiloso", eng: "stylish", hint: "", id: "VDN201" },
  { spanish: "contemporáneo", eng: "contemporary", hint: "", id: "RXJ784" },
  { spanish: "extravagante", eng: "extravagant", hint: "", id: "EPG780" },
  { spanish: "íntimo", eng: "intimate", hint: "", id: "BOE557" },
  { spanish: "vibrante", eng: "vibrant", hint: "", id: "TCK574" },
  { spanish: "zen", eng: "zen", hint: "", id: "XJD676" },
  { spanish: "innovador", eng: "innovative", hint: "", id: "TCE831" },
  { spanish: "de alta gama", eng: "high-end", hint: "", id: "MUX503" },
];
