export const BusinessTerms = [
  { spa: "financiero", eng: "financial", hint: "", id: "ZHI555" },
  { spa: "económico", eng: "economic", hint: "", id: "TRX858" },
  { spa: "rentable", eng: "profitable", hint: "", id: "HPM667" },
  { spa: "sostenible", eng: "sustainable", hint: "", id: "YQT074" },
  { spa: "competitivo", eng: "competitive", hint: "", id: "VHM949" },
  { spa: "innovador", eng: "innovative", hint: "", id: "EYQ257" },
  { spa: "estratégico", eng: "strategic", hint: "", id: "ALY577" },
  { spa: "global", eng: "global", hint: "", id: "MCV046" },
  { spa: "local", eng: "local", hint: "", id: "VPT506" },
  { spa: "corporativo", eng: "corporate", hint: "", id: "FTN477" },
  { spa: "eficiente", eng: "efficient", hint: "", id: "SPJ974" },
  { spa: "dinámico", eng: "dynamic", hint: "", id: "ISC707" },
  { spa: "lucrativo", eng: "lucrative", hint: "", id: "QWC929" },
  { spa: "comercializable", eng: "marketable", hint: "", id: "DOY010" },
  { spa: "emprendedor", eng: "entrepreneurial", hint: "", id: "VUA007" },
  { spa: "productivo", eng: "productive", hint: "", id: "HTI159" },
  { spa: "escalable", eng: "scalable", hint: "", id: "BFI633" },
  { spa: "técnico", eng: "technical", hint: "", id: "DMP084" },
  { spa: "consumidor", eng: "consumer", hint: "", id: "JTZ281" },
  { spa: "comercial", eng: "commercial", hint: "", id: "BQQ769" },
  { spa: "prometedor", eng: "promising", hint: "", id: "IBX673" },
  { spa: "profesional", eng: "professional", hint: "", id: "BHI688" },
  { spa: "operativo", eng: "operational", hint: "", id: "NQF087" },
  { spa: "monetario", eng: "monetary", hint: "", id: "TIJ026" },
  {
    spa: "de alto crecimiento",
    eng: "high-growth",
    hint: "",
    id: "MGE393",
  },
  { spa: "exitoso", eng: "successful", hint: "", id: "WWQ598" },
  { spa: "desafiante", eng: "challenging", hint: "", id: "TLR957" },
  { spa: "revolucionario", eng: "revolutionary", hint: "", id: "PLG197" },
  { spa: "tendencia", eng: "trending", hint: "", id: "RDF666" },
  { spa: "expansivo", eng: "expansive", hint: "", id: "TMV099" },
  { spa: "de vanguardia", eng: "cutting-edge", hint: "", id: "KSY399" },
  { spa: "transformador", eng: "transformative", hint: "", id: "MUY748" },
  { spa: "emergente", eng: "emerging", hint: "", id: "KCL486" },
  { spa: "competitivo", eng: "competitive", hint: "", id: "RAR707" },
  { spa: "flexible", eng: "flexible", hint: "", id: "WMU472" },
  { spa: "estable", eng: "stable", hint: "", id: "JHQ945" },
  { spa: "ético", eng: "ethical", hint: "", id: "ECI127" },
  { spa: "táctico", eng: "tactical", hint: "", id: "UPH403" },
  { spa: "valioso", eng: "valuable", hint: "", id: "YOX550" },
  { spa: "premium", eng: "premium", hint: "", id: "BLX307" },
  { spa: "diverso", eng: "diverse", hint: "", id: "PNW957" },
  { spa: "resiliente", eng: "resilient", hint: "", id: "OTC931" },
  { spa: "duradero", eng: "enduring", hint: "", id: "LUJ072" },
  { spa: "creciente", eng: "growing", hint: "", id: "ESD999" },
  { spa: "optimizado", eng: "streamlined", hint: "", id: "QRN155" },
  { spa: "moderno", eng: "modern", hint: "", id: "UYA001" },
  {
    spa: "impulsado por datos",
    eng: "data-driven",
    hint: "",
    id: "YFY314",
  },
  { spa: "integrador", eng: "integrative", hint: "", id: "JBR341" },
  {
    spa: "de mentalidad progresista",
    eng: "forward-thinking",
    hint: "",
    id: "YWD403",
  },
  { spa: "colaborativo", eng: "collaborative", hint: "", id: "HHL680" },
  { spa: "destacado", eng: "prominent", hint: "", id: "HHK429" },
  { spa: "de buena reputación", eng: "reputable", hint: "", id: "OOK721" },
  { spa: "innovador", eng: "innovative", hint: "", id: "JEZ919" },
];
