export const ClimateConcepts = [
  { spa: "soleado", eng: "sunny", hint: "", id: "ESS085" },
  { spa: "lluvioso", eng: "rainy", hint: "", id: "BIZ487" },
  { spa: "ventoso", eng: "windy", hint: "", id: "POQ154" },
  { spa: "nublado", eng: "cloudy", hint: "", id: "EVQ124" },
  { spa: "stormy", eng: "tormentoso", hint: "", id: "NGG975" },
  { spa: "nublado", eng: "overcast", hint: "", id: "HBC546" },
  { spa: "con neblina", eng: "foggy", hint: "", id: "HOG483" },
  { spa: "caluroso", eng: "scorching", hint: "", id: "UEH257" },
  { spa: "helado", eng: "freezing", hint: "", id: "NMO196" },
  { spa: "fresco", eng: "chilly", hint: "", id: "WPZ972" },
  { spa: "con brisa", eng: "breezy", hint: "", id: "XRO298" },
  { spa: "húmedo", eng: "muggy", hint: "", id: "WIH603" },
  { spa: "seco", eng: "dry", hint: "", id: "MKE810" },
  { spa: "templado", eng: "mild", hint: "", id: "ENP642" },
  { spa: "caluroso", eng: "hot", hint: "", id: "WPX137" },
  { spa: "fresco", eng: "cool", hint: "", id: "MFM982" },
  { spa: "cálido", eng: "warm", hint: "", id: "ODM494" },
  { spa: "húmedo", eng: "humid", hint: "", id: "BTJ188" },
  { spa: "ventoso", eng: "blustery", hint: "", id: "WIX102" },
  { spa: "glacial", eng: "glacial", hint: "", id: "DTQ474" },
  { spa: "con truenos", eng: "thundery", hint: "", id: "OGT728" },
  { spa: "sofocante", eng: "sultry", hint: "", id: "NQY127" },
  { spa: "helado", eng: "frosty", hint: "", id: "DLJ900" },
  { spa: "sombrío", eng: "gloomy", hint: "", id: "ANG813" },
  { spa: "lloviznando", eng: "drizzly", hint: "", id: "FRC496" },
  { spa: "húmedo", eng: "damp", hint: "", id: "YAY936" },
];
