export const EconomicConcepts = [
  { spa: "económico", eng: "economic", hint: "", id: "SVJ566" },
  { spa: "financiero", eng: "financial", hint: "", id: "ROM607" },
  { spa: "mercado", eng: "market", hint: "", id: "BMS001" },
  { spa: "global", eng: "global", hint: "", id: "SOW839" },
  { spa: "industrial", eng: "industrial", hint: "", id: "QFV988" },
  { spa: "comercial", eng: "commercial", hint: "", id: "ZIH489" },
  { spa: "monetario", eng: "monetary", hint: "", id: "OOC500" },
  { spa: "costo", eng: "cost", hint: "", id: "IPC899" },
  { spa: "rentable", eng: "profitable", hint: "", id: "GMI635" },
  { spa: "productivo", eng: "productive", hint: "", id: "OJL321" },
  { spa: "competitivo", eng: "competitive", hint: "", id: "KKN528" },
  { spa: "sostenible", eng: "sustainable", hint: "", id: "ZVL098" },
  { spa: "capitalista", eng: "capitalist", hint: "", id: "YZP640" },
  { spa: "económico", eng: "economic", hint: "", id: "TLE556" },
  { spa: "fiscal", eng: "fiscal", hint: "", id: "BAC801" },
  { spa: "productivo", eng: "productive", hint: "", id: "FND039" },
  { spa: "regulatorio", eng: "regulatory", hint: "", id: "QWX162" },
  { spa: "rico", eng: "wealthy", hint: "", id: "FWV630" },
  { spa: "próspero", eng: "prosperous", hint: "", id: "YCF858" },
  { spa: "innovador", eng: "innovative", hint: "", id: "XYA839" },
  { spa: "emergente", eng: "emerging", hint: "", id: "VXO344" },
  { spa: "estancado", eng: "stagnant", hint: "", id: "WZF980" },
  { spa: "volátil", eng: "volatile", hint: "", id: "WRB439" },
  { spa: "fluctuante", eng: "fluctuating", hint: "", id: "MCD611" },
  { spa: "estable", eng: "stable", hint: "", id: "FYW662" },
  { spa: "creciente", eng: "growing", hint: "", id: "CXT789" },
  { spa: "decreciente", eng: "decreasing", hint: "", id: "QEL613" },
  { spa: "expansivo", eng: "expanding", hint: "", id: "NMW270" },
  { spa: "contractivo", eng: "contracting", hint: "", id: "UEA522" },
  { spa: "invertible", eng: "investable", hint: "", id: "UKS716" },
  { spa: "líquido", eng: "liquid", hint: "", id: "NFW030" },
  { spa: "resiliente", eng: "resilient", hint: "", id: "FPX698" },
  { spa: "robusto", eng: "robust", hint: "", id: "OXO698" },
  { spa: "flojo", eng: "slack", hint: "", id: "PPZ951" },
  { spa: "fuerte", eng: "strong", hint: "", id: "XPA178" },
  { spa: "débil", eng: "weak", hint: "", id: "DKN110" },
  { spa: "subdesarrollado", eng: "underdeveloped", hint: "", id: "ALY084" },
  { spa: "desarrollado", eng: "developed", hint: "", id: "LUG587" },
  { spa: "lucrativo", eng: "lucrative", hint: "", id: "LSP007" },
  { spa: "deregulado", eng: "deregulated", hint: "", id: "AIP272" },
  { spa: "libre de aranceles", eng: "tariff-free", hint: "", id: "GIG137" },
  { spa: "exento de impuestos", eng: "tax-free", hint: "", id: "HJR816" },
  { spa: "competitivo", eng: "competitive", hint: "", id: "IIA198" },
  {
    spa: "bien establecido",
    eng: "well-established",
    hint: "",
    id: "XHY700",
  },
  { spa: "subsidiaria", eng: "subsidiary", hint: "", id: "AUE652" },
  { spa: "interconectado", eng: "interconnected", hint: "", id: "BMM239" },
  { spa: "inclusivo", eng: "inclusive", hint: "", id: "OGU162" },
  { spa: "caro", eng: "expensive", hint: "", id: "FOP422" },
  { spa: "económico", eng: "inexpensive", hint: "", id: "LYS586" },
  { spa: "digital", eng: "digital", hint: "", id: "LNC416" },
  { spa: "virtual", eng: "virtual", hint: "", id: "CWF142" },
  { spa: "tradicional", eng: "traditional", hint: "", id: "HTQ935" },
  { spa: "colaborativo", eng: "collaborative", hint: "", id: "SNQ196" },
  { spa: "transformador", eng: "transformative", hint: "", id: "QQX113" },
  { spa: "adaptativo", eng: "adaptive", hint: "", id: "OCR247" },
  { spa: "disruptivo", eng: "disruptive", hint: "", id: "BIX379" },
  { spa: "ineficiente", eng: "inefficient", hint: "", id: "NMW469" },
  { spa: "eficiente", eng: "efficient", hint: "", id: "HKP695" },
  { spa: "sostenible", eng: "sustainable", hint: "", id: "CGN514" },
  { spa: "rentable", eng: "profitable", hint: "", id: "HPW724" },
  { spa: "nonrentable", eng: "unprofitable", hint: "", id: "VCS098" },
  { spa: "estratégico", eng: "strategic", hint: "", id: "MKJ034" },
  { spa: "OPORTUNIDAD", eng: "OPPORTUNITY", hint: "", id: "CZW924" },
  { spa: "no probado", eng: "UNTRIED", hint: "", id: "KPX423" },
  { spa: "DESCONOCIDO", eng: "UNKNOWN", hint: "", id: "HZT234" },
  { spa: "alternativo", eng: "ALTINATE", hint: "", id: "TJB802" },
  { spa: "nuevo", eng: "NEW", hint: "", id: "CBU368" },
  { spa: "especializado", eng: "SPECIALIZED", hint: "", id: "YDC132" },
  { spa: "avanzado", eng: "ADVANCED", hint: "", id: "XCW505" },
  { spa: "variado", eng: "VARIED", hint: "", id: "GNR011" },
  { spa: "multietapa", eng: "MULTI-STAGE", hint: "", id: "VRP480" },
  { spa: "dinámico", eng: "DYNAMIC", hint: "", id: "DRN794" },
];
