export const FitnessActivities = [
  { spa: "activo", eng: "active", hint: "", id: "IWO911" },
  { spa: "en forma", eng: "fit", hint: "", id: "CRC692" },
  { spa: "fuerte", eng: "strong", hint: "", id: "ZVG524" },
  { spa: "flexible", eng: "flexible", hint: "", id: "PRW038" },
  { spa: "ágil", eng: "agile", hint: "", id: "TLL735" },
  { spa: "resistencia", eng: "endurance", hint: "", id: "ZNC685" },
  { spa: "poderoso", eng: "powerful", hint: "", id: "LVG679" },
  { spa: "saludable", eng: "healthy", hint: "", id: "MRN372" },
  { spa: "estamina", eng: "stamina", hint: "", id: "VZQ866" },
  { spa: "rápido", eng: "quick", hint: "", id: "SVR191" },
  { spa: "tonificado", eng: "toned", hint: "", id: "EGD200" },
  { spa: "atlético", eng: "athletic", hint: "", id: "WOT932" },
  { spa: "musculoso", eng: "muscular", hint: "", id: "KNJ433" },
  { spa: "energético", eng: "energetic", hint: "", id: "CVD151" },
  { spa: "resiliente", eng: "resilient", hint: "", id: "WMS802" },
  { spa: "vibrante", eng: "vibrant", hint: "", id: "QNC616" },
  { spa: "robusto", eng: "robust", hint: "", id: "XXF807" },
  { spa: "vital", eng: "vital", hint: "", id: "TCQ639" },
  { spa: "floreciente", eng: "thriving", hint: "", id: "VIQ678" },
  { spa: "dinámico", eng: "dynamic", hint: "", id: "PEL826" },
  { spa: "equilibrado", eng: "balanced", hint: "", id: "RAH297" },
  { spa: "móvil", eng: "mobile", hint: "", id: "JVO425" },
  { spa: "delgado", eng: "lean", hint: "", id: "DNN422" },
  { spa: "constante", eng: "steady", hint: "", id: "GZK151" },
  { spa: "ágil", eng: "nimble", hint: "", id: "BNS621" },
  { spa: "riguroso", eng: "rigorous", hint: "", id: "PJH821" },
  { spa: "duro", eng: "tough", hint: "", id: "UWY749" },
  { spa: "revitalizante", eng: "invigorating", hint: "", id: "MOQ054" },
  { spa: "tonificante", eng: "toning", hint: "", id: "NYL597" },
  { spa: "cardiovascular", eng: "cardiovascular", hint: "", id: "PTZ344" },
  { spa: "restaurador", eng: "restorative", hint: "", id: "YEM374" },
  { spa: "enriquecedor", eng: "enriching", hint: "", id: "DTW168" },
  {
    spa: "que induce sudor",
    eng: "sweat-inducing",
    hint: "",
    id: "VYI208",
  },
  {
    spa: "desarrollo muscular",
    eng: "muscle-building",
    hint: "",
    id: "UYO008",
  },
  {
    spa: "de alta intensidad",
    eng: "high-intensity",
    hint: "",
    id: "YBG158",
  },
  { spa: "de bajo impacto", eng: "low-impact", hint: "", id: "OQG312" },
  {
    spa: "activador cardiovascular",
    eng: "heart-pumping",
    hint: "",
    id: "YNW368",
  },
  { spa: "quemacalorías", eng: "calorie-burning", hint: "", id: "JQA682" },
];
