export const Footwear = [
  { spa: "elegante", eng: "stylish", hint: "", id: "ZJI664" },
  { spa: "cómodo", eng: "comfortable", hint: "", id: "SPZ694" },
  { spa: "duradero", eng: "durable", hint: "", id: "VCY601" },
  { spa: "de moda", eng: "fashionable", hint: "", id: "CWO666" },
  { spa: "versátil", eng: "versatile", hint: "", id: "HIF179" },
  { spa: "acogedor", eng: "cozy", hint: "", id: "CNF619" },
  { spa: "casual", eng: "casual", hint: "", id: "UHI287" },
  { spa: "práctico", eng: "practical", hint: "", id: "ZIF143" },
  { spa: "elegante", eng: "elegant", hint: "", id: "KJI872" },
  { spa: "chic", eng: "chic", hint: "", id: "NYD409" },
  { spa: "deportivo", eng: "sporty", hint: "", id: "BXF713" },
  { spa: "de moda", eng: "trendy", hint: "", id: "RIV672" },
  { spa: "atlético", eng: "athletic", hint: "", id: "XKB256" },
  { spa: "llamativo", eng: "funky", hint: "", id: "JJT850" },
  { spa: "elegante", eng: "classy", hint: "", id: "QXZ162" },
  { spa: "estilizado", eng: "sleek", hint: "", id: "ALM126" },
  { spa: "moderno", eng: "modern", hint: "", id: "CNX945" },
  { spa: "tradicional", eng: "traditional", hint: "", id: "JTH216" },
  { spa: "de soporte", eng: "supportive", hint: "", id: "ABP101" },
  { spa: "robusto", eng: "sturdy", hint: "", id: "ZGK556" },
  { spa: "lusioso", eng: "luxurious", hint: "", id: "QGL686" },
  { spa: "económico", eng: "affordable", hint: "", id: "TTP263" },
  { spa: "innovador", eng: "trendsetting", hint: "", id: "HEL652" },
  { spa: "ajustado", eng: "fitted", hint: "", id: "OBJ105" },
  { spa: "funcional", eng: "functional", hint: "", id: "IYG214" },
  { spa: "premium", eng: "premium", hint: "", id: "KYQ848" },
  { spa: "atemporal", eng: "timeless", hint: "", id: "YLH934" },
  { spa: "único", eng: "unique", hint: "", id: "BMP615" },
  { spa: "vibrante", eng: "vibrant", hint: "", id: "YLQ265" },
  { spa: "atractivo", eng: "attractive", hint: "", id: "GST721" },
  { spa: "sofisticado", eng: "sophisticated", hint: "", id: "FLN947" },
  { spa: "sensato", eng: "sensible", hint: "", id: "IPF218" },
  { spa: "liviano", eng: "lightweight", hint: "", id: "OHI512" },
  { spa: "impermeable", eng: "waterproof", hint: "", id: "NJU830" },
  { spa: "transpirable", eng: "breathable", hint: "", id: "USW804" },
];
