export const PartsOfVehicles = [
  { spa: "rápido", eng: "fast", hint: "", id: "OWY589" },
  { spa: "lento", eng: "slow", hint: "", id: "PKS528" },
  { spa: "confiable", eng: "reliable", hint: "", id: "KIF728" },
  { spa: "eficiente", eng: "efficient", hint: "", id: "COI229" },
  { spa: "espacioso", eng: "spacious", hint: "", id: "BJX915" },
  { spa: "compacto", eng: "compact", hint: "", id: "GPS321" },
  { spa: "moderno", eng: "modern", hint: "", id: "JZX951" },
  { spa: "vintage", eng: "vintage", hint: "", id: "SOG722" },
  { spa: "de lujo", eng: "luxurious", hint: "", id: "DIE615" },
  { spa: "pequeño", eng: "small", hint: "", id: "KWB320" },
  { spa: "grande", eng: "large", hint: "", id: "XOT715" },
  { spa: "eléctrico", eng: "electric", hint: "", id: "PSL210" },
  { spa: "potente", eng: "powerful", hint: "", id: "TBH540" },
  { spa: "manual", eng: "manual", hint: "", id: "VAZ959" },
  { spa: "automático", eng: "automatic", hint: "", id: "HIV458" },
  { spa: "aerodinámico", eng: "aerodynamic", hint: "", id: "JCZ969" },
  { spa: "elegante", eng: "sleek", hint: "", id: "GEU483" },
  { spa: "resistente", eng: "rugged", hint: "", id: "OQG162" },
  { spa: "aerodinámico", eng: "streamlined", hint: "", id: "FJD051" },
  { spa: "resistente", eng: "sturdy", hint: "", id: "ZLJ461" },
  { spa: "ágil", eng: "agile", hint: "", id: "KYZ758" },
  { spa: "cómodo", eng: "comfortable", hint: "", id: "GWI075" },
  { spa: "espacioso", eng: "roomy", hint: "", id: "NTI266" },
  { spa: "funcional", eng: "functional", hint: "", id: "WZL374" },
  { spa: "ergonómico", eng: "ergonomic", hint: "", id: "URU836" },
  { spa: "elegante", eng: "stylish", hint: "", id: "AJK150" },
  { spa: "económico", eng: "economical", hint: "", id: "QAP174" },
  { spa: "versátil", eng: "versatile", hint: "", id: "VHT738" },
  { spa: "avanzado", eng: "advanced", hint: "", id: "PYD969" },
  { spa: "de alta tecnología", eng: "hi-tech", hint: "", id: "XUK137" },
  {
    spa: "amigable con el medio ambiente",
    eng: "eco-friendly",
    hint: "",
    id: "QYO661",
  },
  {
    spa: "de alto rendimiento",
    eng: "high-performance",
    hint: "",
    id: "BEC423",
  },
  { spa: "seguro", eng: "safe", hint: "", id: "FJH298" },
  { spa: "emocionante", eng: "exciting", hint: "", id: "VYE678" },
  { spa: "personalizado", eng: "customized", hint: "", id: "IEM098" },
  { spa: "de servicio pesado", eng: "heavy-duty", hint: "", id: "ZDO204" },
  { spa: "compacto", eng: "compact", hint: "", id: "FBA754" },
  { spa: "conectado", eng: "connected", hint: "", id: "JLK620" },
  { spa: "innovador", eng: "innovative", hint: "", id: "ZSF963" },
  { spa: "ligero", eng: "lightweight", hint: "", id: "RGB430" },
  {
    spa: "eficiente en combustible",
    eng: "fuel-efficient",
    hint: "",
    id: "CSO544",
  },
  { spa: "todo terreno", eng: "off-road", hint: "", id: "OJM958" },
  {
    spa: "amigable con la ciudad",
    eng: "city-friendly",
    hint: "",
    id: "HOC314",
  },
  { spa: "confiable", eng: "reliable", hint: "", id: "OBO252" },
  {
    spa: "bajo mantenimiento",
    eng: "low-maintenance",
    hint: "",
    id: "REF761",
  },
  { spa: "duradero", eng: "durable", hint: "", id: "HMA809" },
];
