export const PhysicalSensations = [
  { spa: "feliz", eng: "happy ", hint: "", id: "MGC565" },
  { spa: "triste", eng: "sad ", hint: "", id: "VHL823" },
  { spa: "enojado", eng: "angry ", hint: "", id: "UDK861" },
  { spa: "emocionado", eng: "excited ", hint: "", id: "YQO610" },
  { spa: "ansioso", eng: "anxious ", hint: "", id: "FEL274" },
  { spa: "nervioso", eng: "nervous ", hint: "", id: "HRA332" },
  { spa: "relajado", eng: "relaxed ", hint: "", id: "BKG163" },
  { spa: "frustrado", eng: "frustrated ", hint: "", id: "XRJ568" },
  { spa: "agradecido", eng: "grateful ", hint: "", id: "LNG064" },
  { spa: "culpable", eng: "guilty ", hint: "", id: "LNR218" },
  { spa: "celoso", eng: "jealous ", hint: "", id: "RPE949" },
  { spa: "esperanzado", eng: "hopeful ", hint: "", id: "MFK554" },
  { spa: "entusiasta", eng: "enthusiastic ", hint: "", id: "MEL122" },
  { spa: "decepcionado", eng: "disappointed ", hint: "", id: "YPC564" },
  { spa: "contento", eng: "content ", hint: "", id: "DVE440" },
  { spa: "inquieto", eng: "restless ", hint: "", id: "APP109" },
  { spa: "orgulloso", eng: "proud ", hint: "", id: "HZP800" },
  { spa: "avergonzado", eng: "ashamed ", hint: "", id: "KDP266" },
  { spa: "aburrido", eng: "bored ", hint: "", id: "UNK218" },
  { spa: "confundido", eng: "confused ", hint: "", id: "IFW747" },
  { spa: "sorprendido", eng: "surprised ", hint: "", id: "GUI215" },
  { spa: "avergonzado", eng: "embarrassed ", hint: "", id: "SSR698" },
  { spa: "solo", eng: "lonely ", hint: "", id: "AIN584" },
  { spa: "amado", eng: "loved ", hint: "", id: "EEO888" },
  { spa: "rechazado", eng: "rejected ", hint: "", id: "BFA058" },
  { spa: "abrumado", eng: "overwhelmed ", hint: "", id: "SSR171" },
];
