export const TimeRelatedConcepts = [
  { spa: "pasado", eng: "past", hint: "", id: "VNX637" },
  { spa: "presente", eng: "present", hint: "", id: "JTM635" },
  { spa: "futuro", eng: "future", hint: "", id: "ZCI059" },
  { spa: "diario", eng: "daily", hint: "", id: "KFV456" },
  { spa: "semanal", eng: "weekly", hint: "", id: "KGL739" },
  { spa: "mensual", eng: "monthly", hint: "", id: "QON213" },
  { spa: "anual", eng: "annual", hint: "", id: "ZAS382" },
  { spa: "oportuno", eng: "timely", hint: "", id: "AWB833" },
  { spa: "atemporal", eng: "timeless", hint: "", id: "YAX624" },
  { spa: "temporal", eng: "temporary", hint: "", id: "BLO670" },
  { spa: "eterno", eng: "eternal", hint: "", id: "FRH536" },
  { spa: "cronológico", eng: "chronological", hint: "", id: "TFP186" },
  { spa: "histórico", eng: "historic", hint: "", id: "ULH890" },
  { spa: "moderno", eng: "modern", hint: "", id: "FTN012" },
  { spa: "antiguo", eng: "ancient", hint: "", id: "LQM382" },
  { spa: "contemporáneo", eng: "contemporary", hint: "", id: "QWG801" },
  { spa: "reciente", eng: "recent", hint: "", id: "QXS189" },
  { spa: "momentáneo", eng: "momentary", hint: "", id: "UAL280" },
  { spa: "duradero", eng: "lasting", hint: "", id: "PXG244" },
  { spa: "urgente", eng: "urgent", hint: "", id: "JID126" },
  { spa: "a largo plazo", eng: "long-term", hint: "", id: "BGU217" },
  { spa: "a corto plazo", eng: "short-term", hint: "", id: "JPN195" },
  { spa: "vinculado al tiempo", eng: "time-bound", hint: "", id: "VTQ107" },
  {
    spa: "sensible al tiempo",
    eng: "time-sensitive",
    hint: "",
    id: "JIH105",
  },
  {
    spa: "que consume tiempo",
    eng: "time-consuming",
    hint: "",
    id: "GEK036",
  },
  { spa: "oportuno", eng: "timely", hint: "", id: "ONA517" },
  {
    spa: "de antigua tradición",
    eng: "time-honored",
    hint: "",
    id: "WSK817",
  },
  { spa: "intemporal", eng: "timeless", hint: "", id: "JWI936" },
  { spa: "intemporal", eng: "timeless", hint: "", id: "EHT912" },
  { spa: "segundo", eng: "second", hint: "", id: "QZG538" },
  { spa: "tercero", eng: "third", hint: "", id: "VGE058" },
  { spa: "cuarto", eng: "fourth", hint: "", id: "CNT888" },
  { spa: "quinto", eng: "fifth", hint: "", id: "PYD324" },
  { spa: "temprano", eng: "early", hint: "", id: "RSC395" },
  { spa: "a mitad de semana", eng: "midweek", hint: "", id: "RLB810" },
  { spa: "fin de semana", eng: "weekend", hint: "", id: "MEJ871" },
  { spa: "de una semana", eng: "weeklong", hint: "", id: "JVJ332" },
  { spa: "diario", eng: "daily", hint: "", id: "GHL431" },
  { spa: "nocturno", eng: "nightly", hint: "", id: "MUY290" },
  { spa: "cada hora", eng: "hourly", hint: "", id: "UQD566" },
  { spa: "semanal", eng: "weekly", hint: "", id: "NJU155" },
  { spa: "cada quincena", eng: "fortnightly", hint: "", id: "FJF387" },
  { spa: "mensual", eng: "monthly", hint: "", id: "MYM881" },
  { spa: "anualmente", eng: "annually", hint: "", id: "HEY034" },
  { spa: "trimestral", eng: "quarterly", hint: "", id: "NGO291" },
  { spa: "perenne", eng: "perennial", hint: "", id: "XRL932" },
  {
    spa: "viajero del tiempo",
    eng: "time-travelling",
    hint: "",
    id: "YEJ847",
  },
  {
    spa: "con retraso en el tiempo",
    eng: "time-delayed",
    hint: "",
    id: "CUN069",
  },
  {
    spa: "sensible al tiempo",
    eng: "time-sensitive",
    hint: "",
    id: "GCB478",
  },
  {
    spa: "bajo presión de tiempo",
    eng: "time-crunched",
    hint: "",
    id: "ZPP689",
  },
  {
    spa: "que hace perder tiempo",
    eng: "time-wasting",
    hint: "",
    id: "KRM152",
  },
  {
    spa: "de un año de duración",
    eng: "year-long",
    hint: "",
    id: "RGK937",
  },
  {
    spa: "de décadas de antigüedad",
    eng: "decades-old",
    hint: "",
    id: "INN398",
  },
  {
    spa: "de siglos de antigüedad",
    eng: "century-old",
    hint: "",
    id: "YOL741",
  },
  {
    spa: "de milenios de antigüedad",
    eng: "millennium-old",
    hint: "",
    id: "BMM244",
  },
];
