export const ToolsAndEquipment = [
  { spa: "afilado", eng: "sharp", hint: "", id: "YAK002" },
  { spa: "durable", eng: "durable", hint: "", id: "NNZ733" },
  { spa: "portátil", eng: "portable", hint: "", id: "WUS128" },
  { spa: "eléctrico", eng: "electric", hint: "", id: "KXR007" },
  { spa: "resistente", eng: "heavy-duty", hint: "", id: "ICD780" },
  { spa: "ergonómico", eng: "ergonomic", hint: "", id: "FUM613" },
  { spa: "ajustable", eng: "adjustable", hint: "", id: "MFC145" },
  { spa: "retráctil", eng: "retractable", hint: "", id: "ZWF280" },
  { spa: "compacto", eng: "compact", hint: "", id: "TXJ394" },
  { spa: "potente", eng: "powerful", hint: "", id: "UCZ359" },
  { spa: "versátil", eng: "versatile", hint: "", id: "ZPP504" },
  { spa: "eficiente", eng: "efficient", hint: "", id: "GYI625" },
  { spa: "inalámbrico", eng: "cordless", hint: "", id: "DGN405" },
  { spa: "automático", eng: "automatic", hint: "", id: "VCE650" },
  { spa: "precisión", eng: "precision", hint: "", id: "GXF359" },
  { spa: "ergonómico", eng: "ergonomic", hint: "", id: "MSU813" },
  { spa: "industrial", eng: "industrial", hint: "", id: "EWF602" },
  { spa: "práctico", eng: "handy", hint: "", id: "NZL465" },
  {
    spa: "multifuncional",
    eng: "multi-functional",
    hint: "",
    id: "NUO574",
  },
  { spa: "compacto", eng: "compact", hint: "", id: "SSY719" },
  { spa: "de alta calidad", eng: "high-quality", hint: "", id: "LGQ128" },
  { spa: "innovador", eng: "innovative", hint: "", id: "UIA688" },
  { spa: "confiable", eng: "reliable", hint: "", id: "JLE858" },
  { spa: "robusto", eng: "robust", hint: "", id: "REO151" },
  { spa: "resistente", eng: "sturdy", hint: "", id: "SYZ804" },
  { spa: "automatizado", eng: "automated", hint: "", id: "XIR372" },
  { spa: "manual", eng: "manual", hint: "", id: "HEV297" },
  { spa: "ergonómico", eng: "ergonomic", hint: "", id: "YIA919" },
  { spa: "ergonómico", eng: "ergonomic", hint: "", id: "UPJ282" },
];
