export const WeatherAndClimate = [
  { spa: "soleado", eng: "sunny", hint: "", id: "WJU089" },
  { spa: "nublado", eng: "cloudy", hint: "", id: "HMW515" },
  { spa: "lluvioso", eng: "rainy", hint: "", id: "QJE843" },
  { spa: "tormentoso", eng: "stormy", hint: "", id: "BAY113" },
  { spa: "ventoso", eng: "windy", hint: "", id: "IEB048" },
  { spa: "nevado", eng: "snowy", hint: "", id: "LUK050" },
  { spa: "neblinoso", eng: "foggy", hint: "", id: "PRV246" },
  { spa: "brumoso", eng: "hazy", hint: "", id: "YYP359" },
  { spa: "nublado", eng: "overcast", hint: "", id: "HBY570" },
  { spa: "despejado", eng: "clear", hint: "", id: "ZLP506" },
  { spa: "húmedo", eng: "humid", hint: "", id: "DTC309" },
  { spa: "seco", eng: "dry", hint: "", id: "ULW478" },
  { spa: "húmedo", eng: "damp", hint: "", id: "NJH960" },
  { spa: "bochornoso", eng: "muggy", hint: "", id: "JEZ974" },
  { spa: "ventoso", eng: "breezy", hint: "", id: "TIA190" },
  { spa: "fresco", eng: "chilly", hint: "", id: "PVS335" },
  { spa: "caluroso", eng: "hot", hint: "", id: "RZD655" },
  { spa: "templado", eng: "warm", hint: "", id: "WGD829" },
  { spa: "fresco", eng: "cool", hint: "", id: "DXD900" },
  { spa: "helado", eng: "freezing", hint: "", id: "MFK269" },
  { spa: "ventoso", eng: "blustery", hint: "", id: "BKZ039" },
  { spa: "templado", eng: "mild", hint: "", id: "FAO834" },
  { spa: "sombrío", eng: "gloomy", hint: "", id: "DRK555" },
  { spa: "turbulento", eng: "thunderous", hint: "", id: "QWH949" },
  { spa: "torrencial", eng: "torrential", hint: "", id: "ERU200" },
  { spa: "lloviznoso", eng: "drizzly", hint: "", id: "RIF047" },
];
