export const Cooperation = [
  { spa: "ayuda", eng: "help", hint: "", id: "HAF085" },
  { spa: "trabajar juntos", eng: "work together", hint: "", id: "BTN156" },
  { spa: "apoyar", eng: "support", hint: "", id: "TTL874" },
  { spa: "cooperar", eng: "cooperate", hint: "", id: "YUK340" },
  { spa: "coordinar", eng: "coordinate", hint: "", id: "XNU569" },
  { spa: "ayudar", eng: "assist", hint: "", id: "XUI161" },
  { spa: "asistir", eng: "aid", hint: "", id: "BRE228" },
  { spa: "contribuir", eng: "contribute", hint: "", id: "XWZ401" },
  { spa: "echar una mano", eng: "pitch in", hint: "", id: "TID640" },
  { spa: "trabajar en equipo", eng: "team up", hint: "", id: "IZF142" },
  { spa: "fusionar", eng: "merge", hint: "", id: "KYX726" },
  { spa: "unir", eng: "unite", hint: "", id: "PKC817" },
  {
    spa: "combinar esfuerzos",
    eng: "combine efforts",
    hint: "",
    id: "OXK311",
  },
  {
    spa: "estar al servicio",
    eng: "be of service",
    hint: "",
    id: "NSF157",
  },
  { spa: "echar una mano", eng: "lend a hand", hint: "", id: "VQA969" },
  { spa: "unir fuerzas", eng: "join forces", hint: "", id: "QTA048" },
  { spa: "unir esfuerzos", eng: "pull together", hint: "", id: "RTJ052" },
  { spa: "unirse", eng: "come together", hint: "", id: "VJQ012" },
  { spa: "socio", eng: "partner", hint: "", id: "FVH005" },
  { spa: "aliado", eng: "ally", hint: "", id: "NFT923" },
  {
    spa: "meter recursos en común",
    eng: "pool resources",
    hint: "",
    id: "IOR932",
  },
  { spa: "mezclar", eng: "blend", hint: "", id: "XYT848" },
  { spa: "sinergizar", eng: "synergize", hint: "", id: "WLV079" },
  { spa: "conectar", eng: "connect", hint: "", id: "PTI474" },
  {
    spa: "mostrar solidaridad",
    eng: "show solidarity",
    hint: "",
    id: "YFZ252",
  },
  { spa: "ser compinche", eng: "buddy up", hint: "", id: "GIM878" },
  { spa: "embarcarse", eng: "get on board", hint: "", id: "INK870" },
  {
    spa: "estar en contubernio",
    eng: "be in cahoots",
    hint: "",
    id: "RBM775",
  },
  {
    spa: "permanecer unidos",
    eng: "stick together",
    hint: "",
    id: "DCX263",
  },
  {
    spa: "poner cabezas juntas",
    eng: "put heads together",
    hint: "",
    id: "ZAL964",
  },
  { spa: "ser de ayuda", eng: "be of assistance", hint: "", id: "FNB190" },
];
