export const Locomotion = [
  { spa: "caminar", eng: "walk", hint: "", id: "ZJM911" },
  { spa: "correr", eng: "run", hint: "", id: "PZO468" },
  { spa: "trotar", eng: "jog", hint: "", id: "TDR470" },
  { spa: "sprint", eng: "sprint", hint: "", id: "SGI821" },
  { spa: "caminata", eng: "hike", hint: "", id: "OWX250" },
  { spa: "escalar", eng: "climb", hint: "", id: "DIY560" },
  { spa: "arrastrarse", eng: "crawl", hint: "", id: "IZW793" },
  { spa: "brincar", eng: "skip", hint: "", id: "NLM837" },
  { spa: "saltar", eng: "jump", hint: "", id: "ABK358" },
  { spa: "levitar", eng: "levitate", hint: "", id: "JLG921" },
  { spa: "volar", eng: "fly", hint: "", id: "VEM699" },
  { spa: "deslizarse", eng: "glide", hint: "", id: "UTD122" },
  { spa: "flotar", eng: "float", hint: "", id: "ZVF153" },
  { spa: "nadar", eng: "swim", hint: "", id: "VJV254" },
  { spa: "bucear", eng: "dive", hint: "", id: "NKY812" },
  { spa: "navegar", eng: "sail", hint: "", id: "TPO531" },
  { spa: "viajar en crucero", eng: "cruise", hint: "", id: "ALD147" },
  { spa: "remar", eng: "paddle", hint: "", id: "HDV048" },
  { spa: "remar", eng: "row", hint: "", id: "VCJ372" },
  { spa: "andar en canoa", eng: "canoe", hint: "", id: "NIW670" },
  { spa: "andar en kayak", eng: "kayak", hint: "", id: "CJP714" },
  { spa: "andar en balsa", eng: "raft", hint: "", id: "LJW259" },
  { spa: "surfear a vela", eng: "sailboard", hint: "", id: "OEI799" },
  { spa: "patinar", eng: "skate", hint: "", id: "JDS743" },
  { spa: "patinar en tabla", eng: "skateboard", hint: "", id: "VFR006" },
  { spa: "esquiar", eng: "ski", hint: "", id: "PAW408" },
  { spa: "snowboard", eng: "snowboard", hint: "", id: "ZUP138" },
  { spa: "montar", eng: "ride", hint: "", id: "VGF235" },
  { spa: "ciclismo", eng: "cycle", hint: "", id: "GBA196" },
  { spa: "andar en bicicleta", eng: "bike", hint: "", id: "LUQ879" },
  { spa: "andar en bicicleta", eng: "bicycle", hint: "", id: "NMM560" },
  { spa: "patinar", eng: "skate", hint: "", id: "VRQ220" },
  { spa: "patinar en tabla", eng: "skateboard", hint: "", id: "IRJ651" },
  { spa: "esquiar", eng: "ski", hint: "", id: "HLI591" },
  { spa: "snowboard", eng: "snowboard", hint: "", id: "VWY381" },
  { spa: "montar", eng: "ride", hint: "", id: "WSH955" },
  { spa: "conducir", eng: "drive", hint: "", id: "EJK296" },
  { spa: "motocicleta", eng: "motorbike", hint: "", id: "QRE741" },
  { spa: "motocicleta", eng: "motorcycle", hint: "", id: "LUU764" },
  { spa: "scooter", eng: "scooter", hint: "", id: "ELQ387" },
  { spa: "motoneta", eng: "moped", hint: "", id: "AVA880" },
  { spa: "patinar", eng: "skate", hint: "", id: "SXI278" },
  { spa: "patinar en tabla", eng: "skateboard", hint: "", id: "GCA259" },
  { spa: "esquiar", eng: "ski", hint: "", id: "HSV456" },
  { spa: "snowboard", eng: "snowboard", hint: "", id: "DKU086" },
  { spa: "montar", eng: "ride", hint: "", id: "VCU649" },
  { spa: "carrera", eng: "race", hint: "", id: "UWR217" },
  { spa: "ritmo", eng: "pace", hint: "", id: "UIU701" },
  { spa: "viajar", eng: "travel", hint: "", id: "OUL820" },
  { spa: "conmutar", eng: "commute", hint: "", id: "EEN233" },
  { spa: "paseo", eng: "stroll", hint: "", id: "KIP458" },
  { spa: "paseo tranquilo", eng: "amble", hint: "", id: "SEN037" },
  { spa: "paseo tranquilo", eng: "saunter", hint: "", id: "TAC663" },
  { spa: "deambular", eng: "wander", hint: "", id: "RMM145" },
  { spa: "paseo sin rumbo fijo", eng: "ramble", hint: "", id: "JJJ240" },
  { spa: "deambular", eng: "roam", hint: "", id: "RTE486" },
  { spa: "marchar", eng: "march", hint: "", id: "ESR599" },
  { spa: "pasear sin prisa", eng: "mosey", hint: "", id: "IXH710" },
  { spa: "hacer autostop", eng: "hitchhike", hint: "", id: "LZH965" },
  { spa: "trekking", eng: "trek", hint: "", id: "CAM622" },
  { spa: "caminar sin rumbo", eng: "tramp", hint: "", id: "MAN139" },
  { spa: "vadear", eng: "wade", hint: "", id: "BFM858" },
  { spa: "seguir un sendero", eng: "trail", hint: "", id: "HBB311" },
  { spa: "deambular", eng: "meander", hint: "", id: "RJG279" },
  { spa: "bailar un vals", eng: "waltz", hint: "", id: "PQS511" },
  { spa: "galopar", eng: "gallop", hint: "", id: "LUX539" },
  { spa: "trotar", eng: "trot", hint: "", id: "GMO171" },
  { spa: "desplazarse", eng: "locomote", hint: "", id: "HKO585" },
];
