export const Owning = [
  { spa: "tener", eng: "have", hint: "", id: "AXT073" },
  { spa: "poseer", eng: "own", hint: "", id: "PFF320" },
  { spa: "poseer", eng: "possess", hint: "", id: "EKY379" },
  { spa: "adquirir", eng: "acquire", hint: "", id: "OZE852" },
  { spa: "obtener", eng: "obtain", hint: "", id: "AJC879" },
  { spa: "guardar", eng: "keep", hint: "", id: "YZZ084" },
  { spa: "controlar", eng: "control", hint: "", id: "NON339" },
  { spa: "confesar", eng: "own up", hint: "", id: "UMN026" },
  { spa: "ocupar", eng: "occupy", hint: "", id: "YWA176" },
  { spa: "pertencer a", eng: "belong to", hint: "", id: "ZAC049" },
  { spa: "mantener", eng: "retain", hint: "", id: "XXV517" },
  { spa: "heredar", eng: "inherit", hint: "", id: "FON669" },
  { spa: "asegurar", eng: "secure", hint: "", id: "HWJ820" },
  { spa: "reclamar", eng: "claim", hint: "", id: "KIY144" },
  { spa: "aferrar", eng: "clutch", hint: "", id: "TPI690" },
  { spa: "mandar", eng: "command", hint: "", id: "VNE410" },
  { spa: "acorralar", eng: "corner", hint: "", id: "AOU743" },
  { spa: "dominar", eng: "dominate", hint: "", id: "CHP800" },
  { spa: "consagrar", eng: "enshrine", hint: "", id: "LJG430" },
  { spa: "agarrar", eng: "grip", hint: "", id: "IGS512" },
  { spa: "acaparar", eng: "hog", hint: "", id: "JJS905" },
  { spa: "heredar", eng: "inherit", hint: "", id: "ICY057" },
  { spa: "agarrarse", eng: "latch on", hint: "", id: "DGU523" },
  { spa: "encerrar", eng: "lock up", hint: "", id: "PRC228" },
  { spa: "monopolizar", eng: "monopolize", hint: "", id: "NVY466" },
  { spa: "presidir", eng: "preside over", hint: "", id: "JMI741" },
  { spa: "reservar", eng: "reserve", hint: "", id: "GTQ506" },
  { spa: "apoderarse de", eng: "seize", hint: "", id: "RJQ419" },
  { spa: "sentarse en", eng: "sit on", hint: "", id: "JCH919" },
  { spa: "tomar", eng: "take", hint: "", id: "SXN678" },
  { spa: "apoderarse de", eng: "take over", hint: "", id: "XZS980" },
  { spa: "úlcera", eng: "ulcer", hint: "", id: "VHS473" },
  { spa: "susurrar", eng: "whisper", hint: "", id: "VQO518" },
  { spa: "ganar", eng: "win", hint: "", id: "MQN962" },
  { spa: "discutir", eng: "wrangle", hint: "", id: "ZNV364" },
];
