export const Touching = [
  { spa: "tocar", eng: "touch", hint: "", id: "GVE649" },
  { spa: "sentir", eng: "feel", hint: "", id: "DKR691" },
  { spa: "agarrar", eng: "grasp", hint: "", id: "WYG531" },
  { spa: "manejar", eng: "handle", hint: "", id: "POA130" },
  { spa: "acariciar", eng: "caress", hint: "", id: "MXV815" },
  { spa: "acariciar", eng: "stroke", hint: "", id: "CII826" },
  { spa: "dar palmaditas", eng: "pat", hint: "", id: "DJS120" },
  { spa: "tocar ligeramente", eng: "tap", hint: "", id: "YBA938" },
  { spa: "frotar", eng: "rub", hint: "", id: "EMJ233" },
  { spa: "sostener", eng: "hold", hint: "", id: "VIE344" },
  { spa: "apretar", eng: "squeeze", hint: "", id: "AMR110" },
  { spa: "hurgar", eng: "poke", hint: "", id: "HFP144" },
  { spa: "presionar", eng: "press", hint: "", id: "VSI115" },
  { spa: "golpear", eng: "punch", hint: "", id: "BLB901" },
  { spa: "raspar", eng: "scratch", hint: "", id: "SZF222" },
  { spa: "pellizcar", eng: "pinch", hint: "", id: "TXD400" },
  { spa: "empujar", eng: "prod", hint: "", id: "WBI857" },
  { spa: "manosear", eng: "fondle", hint: "", id: "EEK246" },
  { spa: "hacer cosquillas", eng: "tickle", hint: "", id: "USA915" },
  { spa: "rebuscar", eng: "fumble", hint: "", id: "ACE041" },
  { spa: "molestar", eng: "molest", hint: "", id: "SFH763" },
  { spa: "masajear", eng: "massage", hint: "", id: "NNV883" },
  { spa: "amasar", eng: "knead", hint: "", id: "JVE546" },
  { spa: "agarrar", eng: "clutch", hint: "", id: "IXA571" },
  { spa: "saltarse", eng: "skip", hint: "", id: "HNW327" },
  { spa: "cepillar", eng: "brush", hint: "", id: "SIM828" },
  { spa: "empujar ligeramente", eng: "nudge", hint: "", id: "ERY374" },
  { spa: "sostener con el pulgar", eng: "thumb", hint: "", id: "FLD969" },
  { spa: "palpar", eng: "grope", hint: "", id: "URH095" },
  { spa: "golpear con fuerza", eng: "thump", hint: "", id: "EUH851" },
  { spa: "molestar", eng: "tease", hint: "", id: "TRZ614" },
  { spa: "acurrucarse", eng: "cuddle", hint: "", id: "BHQ086" },
  { spa: "manipular", eng: "manipulate", hint: "", id: "IWO744" },
  { spa: "manosear", eng: "manhandle", hint: "", id: "MZD291" },
  { spa: "sostener con el pulgar", eng: "thumb", hint: "", id: "BJX262" },
  { spa: "raspar", eng: "scrape", hint: "", id: "JNO138" },
  { spa: "palpar", eng: "grope", hint: "", id: "JZD920" },
];
