export const Understanding = [
  { spa: "comprender", eng: "understand", hint: "", id: "DRJ921" },
  { spa: "comprender", eng: "comprehend", hint: "", id: "KTB418" },
  { spa: "percibir", eng: "perceive", hint: "", id: "ICY542" },
  { spa: "entender", eng: "grasp", hint: "", id: "AUX676" },
  { spa: "cognizar", eng: "cognize", hint: "", id: "DOA113" },
  { spa: "entender", eng: "fathom", hint: "", id: "KNB701" },
  { spa: "decodificar", eng: "decode", hint: "", id: "EYA913" },
  { spa: "descifrar", eng: "decipher", hint: "", id: "VPN962" },
  { spa: "discernir", eng: "discern", hint: "", id: "DBE942" },
  { spa: "asimilar", eng: "assimilate", hint: "", id: "VWC921" },
  { spa: "absorber", eng: "absorb", hint: "", id: "AHX627" },
  { spa: "internalizar", eng: "internalize", hint: "", id: "WHP656" },
  { spa: "aprehender", eng: "apprehend", hint: "", id: "HVI925" },
  { spa: "procesar", eng: "process", hint: "", id: "ZBV463" },
  { spa: "reconocer", eng: "recognize", hint: "", id: "ZTY041" },
  { spa: "interpretar", eng: "interpret", hint: "", id: "SON535" },
  { spa: "reconocer", eng: "acknowledge", hint: "", id: "TTR354" },
  { spa: "saber", eng: "know", hint: "", id: "IPG175" },
  { spa: "concebir", eng: "conceive", hint: "", id: "SPN008" },
  { spa: "deducir", eng: "deduce", hint: "", id: "NAM115" },
  { spa: "inferir", eng: "infer", hint: "", id: "RGI324" },
  { spa: "construir", eng: "construe", hint: "", id: "DUA341" },
  { spa: "obtener", eng: "glean", hint: "", id: "QHZ725" },
  { spa: "discriminar", eng: "discriminate", hint: "", id: "AVT729" },
  { spa: "anticipar", eng: "anticipate", hint: "", id: "KTF828" },
  { spa: "darse cuenta", eng: "realize", hint: "", id: "FWA413" },
  { spa: "aprender", eng: "learn", hint: "", id: "SGR438" },
  { spa: "imaginar", eng: "envisage", hint: "", id: "TBX727" },
  { spa: "vislumbrar", eng: "envision", hint: "", id: "YDN129" },
  { spa: "entender", eng: "get", hint: "", id: "CBS482" },
  { spa: "comprender", eng: "grok", hint: "", id: "LGD726" },
  { spa: "sentir", eng: "sense", hint: "", id: "FAC685" },
  { spa: "apreciar", eng: "appreciate", hint: "", id: "QMF314" },
  { spa: "detectar", eng: "detect", hint: "", id: "ULW762" },
  { spa: "averiguar", eng: "ascertain", hint: "", id: "WXM722" },
  { spa: "decidir", eng: "decide", hint: "", id: "ODM374" },
  { spa: "descifrar", eng: "figure out", hint: "", id: "VFK252" },
  { spa: "entender", eng: "sort out", hint: "", id: "NAC123" },
  { spa: "entender", eng: "make sense of", hint: "", id: "LYY169" },
  { spa: "analizar", eng: "break down", hint: "", id: "YFD128" },
  { spa: "resolver", eng: "work out", hint: "", id: "KFM442" },
  { spa: "intuir", eng: "intuit", hint: "", id: "HKG066" },
  { spa: "entender", eng: "make out", hint: "", id: "UJL653" },
  { spa: "ver", eng: "see", hint: "", id: "CZR012" },
  { spa: "descubrir", eng: "discover", hint: "", id: "QRN517" },
  { spa: "visualizar", eng: "visualize", hint: "", id: "DLI627" },
  { spa: "imaginar", eng: "imagine", hint: "", id: "IWS756" },
  { spa: "no entender", eng: "fail to understand", hint: "", id: "CTV594" },
  {
    spa: "batallar para entender",
    eng: "struggle to understand",
    hint: "",
    id: "PIW292",
  },
  {
    spa: "captar el significado de",
    eng: "grasp the meaning of",
    hint: "",
    id: "JQM281",
  },
  {
    spa: "ver el punto de",
    eng: "see the point of",
    hint: "",
    id: "IOY446",
  },
  { spa: "internalizar", eng: "internalize", hint: "", id: "BDE978" },
  { spa: "registrarse", eng: "register", hint: "", id: "RTU142" },
  { spa: "captar", eng: "catch on", hint: "", id: "NHJ189" },
  { spa: "darse cuenta", eng: "tumble to", hint: "", id: "XCI080" },
  { spa: "entender", eng: "get the hang of", hint: "", id: "JBV636" },
  { spa: "entender", eng: "get the idea", hint: "", id: "XHU428" },
  { spa: "entender", eng: "get the picture", hint: "", id: "UJS673" },
  {
    spa: "tener conocimiento",
    eng: "have knowledge",
    hint: "",
    id: "RBR125",
  },
];
