export const HobbiesAndInterests = [
  { spanish: "arte", english: "art" },
  { spanish: "manualidades", english: "crafts" },
  { spanish: "fotografía", english: "photography" },
  { spanish: "pintura", english: "painting" },
  { spanish: "dibujo", english: "drawing" },
  { spanish: "bocetos", english: "sketching" },
  { spanish: "escultura", english: "sculpture" },
  { spanish: "costura", english: "sewing" },
  { spanish: "tejer", english: "knitting" },
  { spanish: "crochet", english: "crocheting" },
  { spanish: "acolchado", english: "quilting" },
  { spanish: "cerámica", english: "pottery" },
  { spanish: "joyería", english: "jewelry making" },
  { spanish: "scrapbooking", english: "scrapbooking" },
  { spanish: "origami", english: "origami" },
  { spanish: "caligrafía", english: "calligraphy" },
  { spanish: "carpintería", english: "woodworking" },
  { spanish: "cincelado", english: "whittling" },
  { spanish: "modelado", english: "model making" },
  { spanish: "grabado", english: "printmaking" },
  { spanish: "trabajo en metal", english: "metalworking" },
  { spanish: "horneado", english: "baking" },
  { spanish: "cocina", english: "cooking" },
  { spanish: "asar a la parrilla", english: "grilling" },
  { spanish: "decoración de pasteles", english: "cake decorating" },
  { spanish: "elaboración de dulces", english: "candy making" },
  { spanish: "mezcla de cócteles", english: "cocktail mixing" },
  { spanish: "cata de vinos", english: "wine tasting" },
  { spanish: "elaboración de cerveza", english: "beer brewing" },
  { spanish: "jardinería", english: "gardening" },
  { spanish: "pesca", english: "fishing" },
  { spanish: "senderismo", english: "hiking" },
  { spanish: "campamento", english: "camping" },
  { spanish: "mochilero", english: "backpacking" },
  { spanish: "observación de aves", english: "birdwatching" },
  { spanish: "observación de estrellas", english: "stargazing" },
  { spanish: "astrología", english: "astrology" },
  { spanish: "lectura", english: "reading" },
  { spanish: "escritura", english: "writing" },
  { spanish: "blogging", english: "blogging" },
  { spanish: "llevar un diario", english: "journaling" },
  { spanish: "web design", english: "web design" },
  { spanish: "codificación", english: "coding" },
  { spanish: "programación", english: "programming" },
  { spanish: "videojuegos", english: "video gaming" },
  { spanish: "juegos de mesa", english: "board games" },
  { spanish: "juegos de cartas", english: "card games" },
  { spanish: "rompecabezas", english: "puzzles" },
  { spanish: "crucigramas", english: "crossword puzzles" },
  { spanish: "sudoku", english: "sudoku" },
  { spanish: "juegos de palabras", english: "word games" },
  { spanish: "acertijos", english: "brain teasers" },
  { spanish: "trucos de magia", english: "magic tricks" },
  { spanish: "malabares", english: "juggling" },
  { spanish: "twisting de globos", english: "balloon twisting" },
  { spanish: "payasear", english: "clowning" },
  { spanish: "ventriloquía", english: "ventriloquism" },
  { spanish: "bailar", english: "dancing" },
  { spanish: "cantar", english: "singing" },
  { spanish: "actuar", english: "acting" },
  { spanish: "improvisar", english: "improv" },
  { spanish: "karaoke", english: "karaoke" },
  { spanish: "instrumentos musicales", english: "musical instruments" },
  { spanish: "yoga", english: "yoga" },
  { spanish: "pilates", english: "pilates" },
  { spanish: "aeróbicos", english: "aerobics" },
  { spanish: "zumba", english: "zumba" },
  { spanish: "kickboxing", english: "kickboxing" },
  { spanish: "artes marciales", english: "martial arts" },
  { spanish: "bolos", english: "bowling" },
  { spanish: "billar", english: "billiards" },
  { spanish: "dardos", english: "darts" },
  { spanish: "ping-pong", english: "ping pong" },
  { spanish: "tenis", english: "tennis" },
  { spanish: "bádminton", english: "badminton" },
  { spanish: "voleibol", english: "volleyball" },
  { spanish: "baloncesto", english: "basketball" },
  { spanish: "fútbol", english: "soccer" },
  { spanish: "fútbol americano", english: "football" },
  { spanish: "béisbol", english: "baseball" },
  { spanish: "softbol", english: "softball" },
  { spanish: "golf", english: "golf" },
  { spanish: "natación", english: "swimming" },
  { spanish: "buceo", english: "diving" },
  { spanish: "surf", english: "surfing" },
  { spanish: "skateboarding", english: "skateboarding" },
  { spanish: "snowboard", english: "snowboarding" },
  { spanish: "esquiar", english: "skiing" },
  { spanish: "patinaje sobre hielo", english: "ice skating" },
  { spanish: "patinaje sobre ruedas", english: "roller skating" },
  { spanish: "ciclismo", english: "cycling" },
  { spanish: "ciclismo de montaña", english: "mountain biking" },
  { spanish: "ciclismo de carretera", english: "road biking" },
  { spanish: "correr", english: "running" },
  { spanish: "jogging", english: "jogging" },
  { spanish: "caminar", english: "walking" },
  { spanish: "hurgar", english: "hunting" },
  { spanish: "pescar", english: "fishing" },
  { spanish: "carrera", english: "racing" },
];
