export const TouristAttractions = [
  { spanish: "museo", english: "museum" },
  { spanish: "playa", english: "beach" },
  { spanish: "atracción turística", english: "landmark" },
  { spanish: "castillo", english: "castle" },
  { spanish: "monumento", english: "monument" },
  { spanish: "parque temático", english: "theme park" },
  { spanish: "zoológico", english: "zoo" },
  { spanish: "acuario", english: "aquarium" },
  { spanish: "parque nacional", english: "national park" },
  { spanish: "cascada", english: "waterfall" },
  { spanish: "observatorio", english: "observatory" },
  { spanish: "faro", english: "lighthouse" },
  { spanish: "cueva", english: "cave" },
  { spanish: "catedral", english: "cathedral" },
  { spanish: "palacio", english: "palace" },
  { spanish: "jardín botánico", english: "botanical garden" },
  { spanish: "santuario de vida silvestre", english: "wildlife sanctuary" },
  { spanish: "montaña", english: "mountain" },
  { spanish: "isla", english: "island" },
  { spanish: "resort", english: "resort" },
  { spanish: "parque acuático", english: "water park" },
  { spanish: "reserva natural", english: "natural reserve" },
  { spanish: "sitio arqueológico", english: "archaeological site" },
  { spanish: "sitio del patrimonio", english: "heritage site" },
  { spanish: "sitio histórico", english: "historic site" },
  { spanish: "rascacielos", english: "skyscraper" },
  { spanish: "parque de diversiones", english: "amusement park" },
  { spanish: "cañón", english: "canyon" },
  { spanish: "selva tropical", english: "rainforest" },
  { spanish: "guía", english: "beacon" },
  { spanish: "monumento", english: "memorial" },
  { spanish: "galería de arte", english: "art gallery" },
  { spanish: "viñedo", english: "vineyard" },
  { spanish: "cordillera", english: "mountain range" },
  { spanish: "volcán", english: "volcano" },
  { spanish: "bodega", english: "winery" },
  { spanish: "bosque", english: "forest" },
  { spanish: "parque de esculturas", english: "sculpture park" },
  { spanish: "oceanario", english: "oceanarium" },
  { spanish: "duna de arena", english: "sand dune" },
  { spanish: "centro cultural", english: "cultural center" },
  { spanish: "manantial termal", english: "thermal spring" },
  { spanish: "resort de esquí", english: "ski resort" },
  { spanish: "barco de crucero", english: "cruise ship" },
  { spanish: "plantación de café", english: "coffee plantation" },
  { spanish: "lago", english: "lake" },
  { spanish: "río", english: "river" },
  { spanish: "desierto", english: "desert" },
  { spanish: "parque de vida silvestre", english: "wildlife park" },
  { spanish: "humedal", english: "wetland" },
  { spanish: "jardín de mariposas", english: "butterfly garden" },
  { spanish: "parque acuático", english: "aquapark" },
  { spanish: "centro de descubrimiento", english: "discovery center" },
  { spanish: "parque safari", english: "safari park" },
  { spanish: "costa", english: "waterfront" },
  { spanish: "casa de ópera", english: "opera house" },
  { spanish: "mirador", english: "observatory deck" },
  { spanish: "pueblo histórico", english: "heritage village" },
  { spanish: "monumento a la guerra", english: "war memorial" },
  { spanish: "jardín de hierbas", english: "herb garden" },
  { spanish: "geiser", english: "geyser" },
  { spanish: "mercado de pescado", english: "fish market" },
  { spanish: "costa de un lago", english: "lakeshore" },
  { spanish: "ruinas", english: "ruins" },
  { spanish: "alberca", english: "swimming pool" },
  { spanish: "teleférico", english: "cable car" },
  { spanish: "paso de montaña", english: "mountain pass" },
  { spanish: "mina", english: "mineshaft" },
  { spanish: "distrito de compras", english: "shopping district" },
];
