export const businessTerms = [
  "business",
  "economics",
  "finance",
  "accounting",
  "marketing",
  "management",
  "investment",
  "revenue",
  "profit",
  "loss",
  "income",
  "asset",
  "liability",
  "equity",
  "capital",
  "stock",
  "share",
  "dividend",
  "interest",
  "loan",
  "debt",
  "risk",
  "strategy",
  "plan",
  "project",
  "budget",
  "forecast",
  "market",
  "competition",
  "marketplace",
  "industry",
  "startup",
  "entrepreneur",
  "employee",
  "employer",
  "customer",
  "client",
  "vendor",
  "supplier",
  "partner",
  "stakeholder",
  "shareholder",
  "board",
  "team",
  "executive",
  "manager",
  "leader",
  "consultant",
  "contract",
  "agreement",
  "deal",
  "transaction",
  "negotiation",
  "contractor",
  "merger",
  "acquisition",
  "bankruptcy",
  "profitability",
  "liquidity",
  "supply",
  "demand",
  "commodity",
  "currency",
  "taxation",
  "regulation",
  "monopoly",
  "cartel",
  "corporation",
  "company",
  "firm",
  "organization",
  "enterprise",
  "small business",
  "corporate",
  "retail",
  "wholesale",
  "manufacturer",
  "production",
  "distribution",
  "logistics",
  "inventory",
  "goods",
  "product",
  "service",
  "brand",
  "market share",
  "consumer",
  "clientele",
  "target",
  "segment",
  "advertising",
  "promotion",
  "public relations",
  "social media",
  "digital marketing",
  "sales",
  "revenue",
  "expenses",
  "cost",
  "overhead",
  "profit margin",
  "break even",
  "return on investment",
  "ROI",
  "balance sheet",
  "income statement",
  "cash flow",
  "credit",
  "debit",
  "payment",
  "invoice",
  "receipt",
  "audit",
  "fraud",
  "scam",
  "cybersecurity",
  "risk management",
  "insurance",
  "banking",
  "finance",
  "investment",
  "diversification",
  "portfolio",
  "stocks",
  "bonds",
  "mutual funds",
  "401k",
  "retirement",
  "pension",
  "savings",
  "loan",
  "mortgage",
  "interest rate",
  "credit score",
  "collateral",
  "default",
  "foreclosure",
  "bankruptcy",
  "downturn",
  "recession",
  "depression",
  "recovery",
  "boom",
  "inflation",
  "deflation",
  "GDP",
  "unemployment",
  "employment",
  "job",
  "wages",
  "salary",
  "payroll",
  "benefits",
  "compensation",
  "incentive",
  "bonus",
  "commission",
  "pay raise",
  "promotion",
  "layoff",
  "firing",
  "resignation",
  "workplace",
  "office",
  "workforce",
  "staff",
  "HR",
  "human resources",
  "training",
  "development",
  "performance",
  "evaluation",
  "job satisfaction",
  "employee engagement",
  "workplace culture",
  "mission statement",
  "vision",
  "values",
  "ethics",
  "integrity",
  "CSR",
  "corporate social responsibility",
  "sustainability",
  "environmental",
  "impact",
  "climate change",
  "green",
  "carbon footprint",
  "renewable energy",
  "sustainable practices",
  "social responsibility",
  "society",
  "community",
  "philanthropy",
  "non-profit",
  "NGO",
  "charity",
  "volunteer",
  "donation",
  "fundraising",
  "grant",
  "foundation",
  "corporate giving",
  "social enterprise",
  "ethical business",
  "fair trade",
  "supply chain",
  "transparency",
  "accountability",
  "reporting",
  "conflict of interest",
  "whistleblower",
  "corruption",
  "bribery",
  "fraud",
  "embezzlement",
  "money laundering",
  "insider trading",
  "antitrust",
  "competition law",
  "intellectual property",
  "patent",
  "copyright",
  "trademark",
  "trade secret",
  "licensing",
  "royalties",
  "infringement",
  "lawsuit",
  "litigation",
  "court",
  "judge",
  "verdict",
  "settlement",
  "appeal",
];
