export const internationalRelations = [
  "treaty ",
  "embassy ",
  "diplomacy ",
  "alliance ",
  "negotiation ",
  "conflict ",
  "resolution ",
  "sanction ",
  "tension ",
  "agreement ",
  "summit ",
  "alliance ",
  "coalition ",
  "mediation ",
  "annexation ",
  "reconciliation ",
  "ceasefire ",
  "diplomat ",
  "delegation ",
  "bilateral ",
  "multilateral ",
  "sovereignty ",
  "warfare ",
  "reparation ",
  "territory ",
  "espionage ",
  "coup ",
  "accord ",
  "ratification ",
  "international law ",
  "department of state ",
];
