export const placesOfWorship = [
  "church",
  "mosque",
  "temple",
  "synagogue",
  "cathedral",
  "shrine",
  "chapel",
  "monastery",
  "pagoda",
  "gurdwara",
  "mandir",
  "minaret",
  "sanctuary",
  "abbey",
  "place of worship",
  "tabernacle",
  "moshav",
  "oratory",
  "pantheon",
  "holy place",
  "altar",
  "prayer room",
  "shul",
  "sacred space",
  "sacristy",
  "devotional space",
  "spiritual center",
  "hermitage",
  "temenos",
];
