export const drinks = [
  "coffee",
  "tea",
  "water",
  "soft drink",
  "juice",
  "beer",
  "wine",
  "cocktail",
  "milk",
  "smoothie",
  "energy drink",
  "sports drink",
  "iced tea",
  "lemonade",
  "sparkling water",
  "hot chocolate",
  "milkshake",
  "kombucha",
  "mate",
  "protein shake",
  "punch",
  "fruit punch",
  "ginger ale",
  "root beer",
  "mocha",
  "frappe",
  "cold brew",
  "fruit beer",
  "coconut water",
  "birch water",
  "tamarind drink",
  "cordial",
  "tonic water",
  "soda water",
  "tonic",
  "ginger beer",
  "cola",
  "diet soda",
  "cream soda",
  "club soda",
  "fizzy drink",
  "cider",
  "iced coffee",
];
