export const governmentPositionsAndBodies = [
  "president ",
  "prime minister ",
  "senator ",
  "congressman ",
  "congresswoman ",
  "representative ",
  "congress ",
  "senate ",
  "house of representatives ",
  "cabinet ",
  "minister ",
  "ambassador ",
  "diplomat ",
  "governor ",
  "mayor ",
  "city council ",
  "judge ",
  "jury ",
  "prosecutor ",
  "defendant ",
  "plaintiff ",
  "attorney ",
  "lawyer ",
  "solicitor ",
  "barrister ",
  "witness ",
  "notary ",
  "ombudsman ",
  "regulator ",
  "bureaucrat ",
  "ombudsman ",
  "parliament ",
  "legislature ",
  "committee ",
  "commission ",
  "court ",
  "supreme court ",
  "appeals court ",
  "district court ",
  "magistrate ",
  "sheriff ",
  "marshal ",
  "deputy ",
  "warden ",
  "coroner ",
  "clerk ",
  "constable ",
  "bailiff ",
  "magistrate ",
];
