export const transportationInfrastructure = [
  "road",
  "bridge",
  "highway",
  "freeway",
  "expressway",
  "street",
  "alley",
  "lane",
  "interstate",
  "overpass",
  "underpass",
  "crossover",
  "exit",
  "entrance",
  "roundabout",
  "tunnel",
  "railway",
  "track",
  "train station",
  "subway",
  "metro",
  "bus stop",
  "bus station",
  "airport",
  "helipad",
  "runway",
  "taxiway",
  "terminal",
  "seaport",
  "ferry terminal",
  "marina",
  "pier",
  "dock",
  "harbor",
  "canal",
  "lock",
  "wharf",
  "checkpoint",
  "toll booth",
  "parking lot",
  "parking garage",
  "garage",
  "carport",
  "car park",
  "lot",
  "sidewalk",
  "crosswalk",
  "zebra crossing",
  "bikeway",
  "cycle path",
  "bike lane",
  "pedestrian bridge",
  "pedestrian tunnel",
  "skate park",
  "skateboard ramp",
  "boardwalk",
  "escalator",
  "moving walkway",
  "monorail",
  "gondola",
  "cable car",
  "chairlift",
];
