export const economicConcepts = [
  "economy",
  "market",
  "trade",
  "supply",
  "demand",
  "price",
  "cost",
  "profit",
  "loss",
  "investment",
  "capital",
  "asset",
  "liability",
  "risk",
  "reward",
  "competition",
  "monopoly",
  "oligopoly",
  "monopolistic competition",
  "perfect competition",
  "externalities",
  "subsidy",
  "tax",
  "income",
  "wages",
  "unemployment",
  "GDP",
  "recession",
  "depression",
  "boom",
  "bust",
  "inflation",
  "deflation",
  "government spending",
  "fiscal policy",
  "monetary policy",
  "interest rate",
  "exchange rate",
  "currency",
  "tariff",
  "quota",
  "profit margin",
  "balance of trade",
  "microeconomics",
  "macroeconomics",
  "globalization",
  "deregulation",
  "regulation",
  "entrepreneur",
  "startup",
  "merger",
  "acquisition",
  "bankruptcy",
  "venture capital",
  "stock market",
  "bond",
  "dividend",
  "credit",
  "debit",
  "consumer",
  "producer",
  "elasticity",
  "utility",
  "equilibrium",
  "scarcity",
  "opportunity cost",
  "comparative advantage",
  "barter",
  "black market",
  "white market",
  "grey market",
  "cartel",
  "lobbying",
  "speculation",
  "utility function",
  "industrialization",
  "protectionism",
  "secular stagnation",
  "crowdfunding",
  "price discrimination",
  "dumping",
  "public good",
  "private good",
];
