export const hobbiesAndInterests = [
  "art ",
  "crafts ",
  "photography ",
  "painting ",
  "drawing ",
  "sketching ",
  "sculpture ",
  "sewing ",
  "knitting ",
  "crocheting ",
  "quilting ",
  "pottery ",
  "jewelry making ",
  "scrapbooking ",
  "origami ",
  "calligraphy ",
  "woodworking ",
  "whittling ",
  "model making ",
  "printmaking ",
  "metalworking ",
  "baking ",
  "cooking ",
  "grilling ",
  "cake decorating ",
  "candy making ",
  "cocktail mixing ",
  "wine tasting ",
  "beer brewing ",
  "gardening ",
  "fishing ",
  "hiking ",
  "camping ",
  "backpacking ",
  "birdwatching ",
  "stargazing ",
  "photography ",
  "astrology ",
  "reading ",
  "writing ",
  "blogging ",
  "journaling ",
  "scrapbooking ",
  "calligraphy ",
  "web design ",
  "coding ",
  "programming ",
  "video gaming ",
  "board games ",
  "card games ",
  "puzzles ",
  "crossword puzzles ",
  "sudoku ",
  "word games ",
  "brain teasers ",
  "magic tricks ",
  "juggling ",
  "balloon twisting ",
  "clowning ",
  "ventriloquism ",
  "dancing ",
  "singing ",
  "acting ",
  "improv ",
  "karaoke ",
  "musical instruments ",
  "yoga ",
  "pilates ",
  "aerobics ",
  "zumba ",
  "kickboxing ",
  "martial arts ",
  "bowling ",
  "billiards ",
  "darts ",
  "ping pong ",
  "tennis ",
  "badminton ",
  "volleyball ",
  "basketball ",
  "soccer ",
  "football ",
  "baseball ",
  "softball ",
  "golf ",
  "swimming ",
  "diving ",
  "surfing ",
  "skateboarding ",
  "snowboarding ",
  "skiing ",
  "ice skating ",
  "roller skating ",
  "cycling ",
  "mountain biking ",
  "road biking ",
  "running ",
  "jogging ",
  "walking ",
  "hiking ",
  "hunting",
  "fishing ",
  "racing",
];
