export const medicalProfessions = [
  "doctor",
  "nurse",
  "surgeon",
  "pharmacist",
  "paramedic",
  "midwife",
  "physician",
  "pediatrician",
  "dermatologist",
  "psychiatrist",
  "gynecologist",
  "urologist",
  "oncologist",
  "cardiologist",
  "radiologist",
  "ophthalmologist",
  "orthopedist",
  "endocrinologist",
  "neurologist",
  "dentist",
  "optometrist",
  "audiologist",
  "psychologist",
  "therapist",
  "chiropractor",
  "rehabilitation specialist",
  "anesthesiologist",
  "occupational therapist",
  "physical therapist",
  "speech therapist",
  "veterinarian",
];
