export const modesOfTransport = [
  "car",
  "bus",
  "train",
  "subway",
  "motorcycle",
  "bicycle",
  "plane",
  "boat",
  "ship",
  "ferry",
  "cruise ship",
  "helicopter",
  "truck",
  "van",
  "limousine",
  "taxi",
  "tram",
  "trolley",
  "minivan",
  "jeep",
  "scooter",
  "gondola",
  "tugboat",
  "semiconductor",
  "bulldozer",
  "yacht",
  "airplane",
  "jet",
  "hovercraft",
  "cargo ship",
  "bike",
  "RV",
  "moped",
  "raft",
  "cable car",
  "rickshaw",
  "skateboard",
  "rollerblades",
  "wheelchair",
  "segway",
  "speedboat",
  "sailboat",
  "canoe",
  "kayak",
  "jetski",
  "snowmobile",
  "tractor",
  "fire truck",
  "ambulance",
  "police car",
  "RV",
  "golf cart",
  "forklift",
  "tow truck",
  "streetcar",
  "bulldozer",
  "backhoe",
  "dump truck",
  "garbage truck",
  "pick-up truck",
  "tanker truck",
  "double-decker bus",
  "tour bus",
  "shuttle bus",
  "school bus",
  "motorhome",
  "cement mixer",
  "party bus",
  "rickshaw",
  "golf cart",
  "food truck",
  "ice cream truck",
  "container ship",
  "bobsled",
  "shopping cart",
  "cargo plane",
  "glider",
  "hot air balloon",
  "parachute",
  "zeppelin",
  "monorail",
  "conveyor belt",
  "chairlift",
  "escalator",
  "funicular",
  "elevator",
  "rocket",
  "space shuttle",
  "skis",
  "snowboard",
  "surfboard",
  "windsurfing board",
  "kiteboard",
  "paddleboard",
  "yacht",
  "sailboat",
  "ferry boat",
  "tugboat",
  "catamaran",
];
