export const healthConditions = [
  "Injury ",
  "Illness ",
  "Disease ",
  "Condition ",
  "Disorder ",
  "Syndrome ",
  "Symptom ",
  "Ailment ",
  "Pain ",
  "Sickness ",
  "Infection ",
  "Cancer ",
  "Allergy ",
  "Fever ",
  "Diabetes ",
  "Obesity ",
  "Asthma ",
  "Arthritis ",
  "High blood pressure ",
  "Anxiety ",
  "Depression ",
  "Stress ",
  "Addiction ",
  "Eating disorder ",
  "Migraine ",
  "HIV ",
  "Heart disease ",
  "Stroke ",
  "Alzheimer's ",
  "Parkinson's ",
  "Epilepsy ",
  "Bronchitis ",
  "Insomnia ",
  "Digestive issues ",
  "Respiratory problems ",
  "Muscle strain ",
  "Fracture ",
  "Concussion ",
  "Common cold ",
  "Flu ",
];
