export const healthAndMedicalTerms = [
  "health ",
  "body ",
  "wellness ",
  "wellbeing ",
  "fitness ",
  "nutrition ",
  "exercise ",
  "diet ",
  "symptom ",
  "hospital ",
  "doctor ",
  "nurse ",
  "patient ",
  "medical ",
  "treatment ",
  "prescription ",
  "medication ",
  "therapy ",
  "surgery ",
  "injury ",
  "illness ",
  "disease ",
  "allergy ",
  "immune system ",
  "vaccine ",
  "pharmacy ",
  "emergency ",
  "therapy ",
  "counseling ",
  "sick ",
  "infection ",
  "pain ",
  "diagnosis ",
  "care ",
  "recovery ",
  "test ",
  "virus ",
  "bacteria ",
  "strain ",
  "wound ",
  "sore ",
  "cough ",
  "headache ",
  "fever ",
  "blood ",
  "pressure ",
  "temperature ",
  "chill ",
  "sweat ",
  "heart ",
  "lungs ",
  "brain ",
  "bones ",
  "muscles ",
  "organs ",
  "vessels ",
  "cells ",
  "tissue ",
  "joint ",
  "skin ",
  "hair ",
  "nails ",
  "teeth ",
  "mouth ",
  "throat ",
  "stomach ",
  "liver ",
  "kidney ",
  "brain ",
  "heart ",
  "lungs ",
  "intestine ",
  "spine ",
  "bloodstream ",
  "skeleton ",
  "digestion ",
  "circulation ",
  "respiratory system ",
  "nervous system ",
  "immune system ",
  "cardiovascular system ",
  "muscular system ",
  "skeletal system ",
  "endocrine system ",
  "integumentary system ",
  "organs ",
  "anatomy ",
  "physiology ",
];
