export const legumesAndNuts = [
  "peanuts",
  "walnuts",
  "almonds",
  "cashews",
  "pistachios",
  "hazelnuts",
  "pecans",
  "macadamia nuts",
  "brazil nuts",
  "pine nuts",
  "chestnuts",
  "filberts",
  "marcona almonds",
  "candlenuts",
  "hickory nuts",
  "ginkgo nuts",
  "beechnuts",
  "acorns",
  "baru nuts",
  "bitter nuts",
  "breadnuts",
  "butternuts",
  "shea nuts",
  "water chestnuts",
  "coconut",
  "sacha inchi",
  "tiger nuts",
  "beans",
  "chickpeas",
  "lentils",
  "soybeans",
  "black beans",
  "kidney beans",
  "pinto beans",
  "navy beans",
  "fava beans",
  "lima beans",
  "mung beans",
  "adzuki beans",
  "peas",
  "black-eyed peas",
  "green peas",
  "split peas",
  "red beans",
  "white beans",
  "cannellini beans",
  "garbanzo beans",
  "butter beans",
  "broad beans",
  "runner beans",
  "haricot beans",
  "scarlet runner beans",
  "pink beans",
  "flageolet beans",
  "soy nuts",
  "edamame",
  "peanuts",
  "walnuts",
  "almonds",
  "cashews",
  "pistachios",
  "hazelnuts",
  "pecans",
  "macadamia nuts",
  "brazil nuts",
  "pine nuts",
  "chestnuts",
  "filberts",
  "marcona almonds",
  "candlenuts",
  "hickory nuts",
  "ginkgo nuts",
  "beechnuts",
  "acorns",
  "baru nuts",
  "bitter nuts",
  "breadnuts",
  "butternuts",
  "shea nuts",
  "water chestnuts",
  "coconut",
  "sacha inchi",
  "tiger nuts",
];
