export const mediaTypes = [
  "television",
  "radio",
  "newspaper",
  "magazine",
  "website",
  "podcast",
  "film",
  "movie",
  "video",
  "broadcast",
  "show",
  "program",
  "episode",
  "series",
  "documentary",
  "advertising",
  "commercial",
  "promo",
  "trailer",
  "streaming",
  "channel",
  "station",
  "content",
  "article",
  "blog",
  "vlog",
  "vlogger",
  "journalism",
  "photography",
  "videography",
  "editing",
  "livestream",
  "animation",
  "social media",
  "journal",
  "infomercial",
  "media",
  "press",
  "interview",
  "headline",
  "interviewer",
  "news",
  "publication",
  "journalist",
  "editor",
  "reporter",
  "copywriter",
  "paparazzi",
  "critic",
  "review",
  "publication",
  "column",
  "newscast",
  "wireless",
  "cable",
  "broadband",
  "satellite",
  "reality show",
  "celebrity gossip",
  "tabloid",
  "microblog",
  "media coverage",
  "investigative journalism",
  "reality TV",
  "talk show",
  "reality competition",
  "press release",
];
