export const schoolSubjects = [
  "mathematics",
  "history",
  "science",
  "language arts",
  "physical education",
  "geography",
  "biology",
  "chemistry",
  "physics",
  "computer science",
  "literature",
  "music",
  "art",
  "drama",
  "social studies",
  "economics",
  "psychology",
  "sociology",
  "foreign languages",
  "philosophy",
  "political science",
  "health education",
  "calculus",
  "anatomy",
  "geometry",
  "algebra",
  "statistics",
  "engineering",
  "business",
  "environmental studies",
  "anthropology",
  "archaeology",
  "religious studies",
  "civics",
  "home economics",
  "nutrition",
  "theater",
  "media studies",
  "design",
  "technology",
];
