export const Prepositions = [
  { spanish: "a", english: "to" },
  { spanish: "antes", english: "before" },
  { spanish: "debajo de", english: "under" },
  { spanish: "junto a", english: "next to" },
  { spanish: "con", english: "with" },
  { spanish: "contra", english: "against" },
  { spanish: "de", english: "of" },
  { spanish: "desde", english: "from" },
  { spanish: "originario de", english: "from" },
  { spanish: "desde", english: "since" },
  { spanish: "durante", english: "during" },
  { spanish: "en", english: "in" },
  { spanish: "en", english: "on" },
  { spanish: "entre", english: "between" },
  { spanish: "hacia", english: "towards" },
  { spanish: "hasta", english: "until" },
  { spanish: "por medio de", english: "by means of" },
  { spanish: "para", english: "for" },
  { spanish: "por", english: "by" },
  { spanish: "por medio de", english: "through" },
  { spanish: "según", english: "according to" },
  { spanish: "sin", english: "without" },
  { spanish: "en", english: "on" },
  { spanish: "acerca de", english: "about" },
  { spanish: "después", english: "after" },
  { spanish: "detrás", english: "behind" },
  { spanish: "a través de", english: "through" },
  { spanish: "cerca", english: "near" },
  { spanish: "lejos de", english: "far from" },
  { spanish: "debajo de", english: "under" },
  { spanish: "encima de", english: "on top of" },
  { spanish: "delante de", english: "in front of" },
  { spanish: "detrás", english: "behind" },
  { spanish: "junto a", english: "next to" },
  { spanish: "delante de", english: "in front of" },
  { spanish: "dentro", english: "inside" },
  { spanish: "fuera de", english: "outside of" },
  { spanish: "junto a", english: "next to" },
  { spanish: "respecto a", english: "regarding" },
  { spanish: "a pesar de", english: "despite" },
  { spanish: "alrededor", english: "around" },
  { spanish: "antes", english: "before" },
  { spanish: "después", english: "after" },
  { spanish: "durante", english: "during" },
  { spanish: "debido a", english: "because of" },
  { spanish: "enfrentando", english: "facing" },
  { spanish: "referente a", english: "regarding" },
  { spanish: "debido a", english: "due to" },
  { spanish: "por causa de", english: "because of" },
];
