export const Pronouns = [
  { spanish: "yo", english: "I" },
  { spanish: "tú", english: "you" },
  { spanish: "usted", english: "you" },
  { spanish: "él", english: "he" },
  { spanish: "ella", english: "she" },
  { spanish: "nosotros", english: "we" },
  { spanish: "nosotras", english: "we" },
  { spanish: "ustedes", english: "you all" },
  { spanish: "vosotros", english: "you all" },
  { spanish: "vosotras", english: "you all" },
  { spanish: "ellos", english: "they" },
  { spanish: "ellas", english: "they" },
  { spanish: "mío", english: "mine" },
  { spanish: "mía", english: "mine" },
  { spanish: "mi", english: "mine" },
  { spanish: "míos", english: "mine" },
  { spanish: "tuyo", english: "yours" },
  { spanish: "tuya", english: "yours" },
  { spanish: "tuyos", english: "yours" },
  { spanish: "tuyas", english: "yours" },
  { spanish: "suyo", english: "his/hers/yours" },
  { spanish: "suya", english: "his/hers/yours" },
  { spanish: "suyos", english: "his/hers/yours" },
  { spanish: "suyas", english: "his/hers/yours" },
  { spanish: "nuestro", english: "ours" },
  { spanish: "nuestra", english: "ours" },
  { spanish: "nuestros", english: "ours" },
  { spanish: "nuestras", english: "ours" },
  { spanish: "vuestro", english: "yours" },
  { spanish: "vuestra", english: "yours" },
  { spanish: "vuestros", english: "yours" },
  { spanish: "vuestras", english: "yours" },
  { spanish: "mí", english: "myself" },
  { spanish: "ti", english: "yourself" },
  { spanish: "se", english: "himself/herself/yourself" },
  { spanish: "nosotros mismos", english: "ourselves" },
  { spanish: "ustedes mismos", english: "yourselves" },
  { spanish: "sí mismos", english: "themselves/yourselves" },
  { spanish: "me", english: "me" },
  { spanish: "te", english: "you" },
  { spanish: "lo", english: "him/it" },
  { spanish: "la", english: "her/it" },
  { spanish: "nos", english: "us" },
  { spanish: "ustedes", english: "you all" },
  { spanish: "los", english: "them" },
  { spanish: "las", english: "them" },
  { spanish: "para mí", english: "to/for me" },
  { spanish: "para ti", english: "to/for you" },
  { spanish: "para él/ella/usted", english: "to/for him/her/you" },
  { spanish: "para nosotros", english: "to/for us" },
  { spanish: "para ustedes", english: "to/for you all" },
  { spanish: "para ellos/ellas/ustedes", english: "to/for them/you all" },
  { spanish: "este", english: "this" },
  { spanish: "esta", english: "this" },
  { spanish: "estos", english: "these" },
  { spanish: "estas", english: "these" },
  { spanish: "ese", english: "that" },
  { spanish: "esa", english: "that" },
  { spanish: "esos", english: "those" },
  { spanish: "esas", english: "those" },
  { spanish: "aquel", english: "that" },
  { spanish: "aquella", english: "that" },
  { spanish: "aquellos", english: "those" },
  { spanish: "aquellas", english: "those" },
];
